<?php

namespace GestionSigcerBundle\Repository\opciones;

/**
 * DestinatarioExportacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DestinatarioExportacionRepository extends \Doctrine\ORM\EntityRepository
{
}
