<?php

namespace GestionSigcerBundle\Repository\opciones;

/**
 * EnvaseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnvaseRepository extends \Doctrine\ORM\EntityRepository
{
}
