<?php

namespace GestionSigcerBundle\Repository\opciones;

/**
 * PaisDestinoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaisDestinoRepository extends \Doctrine\ORM\EntityRepository
{
}
