<?php

namespace GestionSigcerBundle\Repository\opciones;

/**
 * ProductoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductoRepository extends \Doctrine\ORM\EntityRepository
{
	public function getArticulosWhitDestino($destino) 
	{ 
	    return $this->createQueryBuilder('p')
	    			->where('p.destino = :destino')
	    			->setParameter('destino', $destino)
			        ->getQuery()
			        ->getResult(); 
	} 
}
