<?php

namespace GestionSigcerBundle\Repository\opciones;

/**
 * ZonaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ZonaRepository extends \Doctrine\ORM\EntityRepository
{
	public function findZonasOfGrupo(\GestionSigcerBundle\Entity\opciones\Region $region) { 
	    return $this->createQueryBuilder('z')
	    			->where('z.region = :region')
	    			->setParameter('region', $region)
			        ->addOrderBy('z.codigo')
			        ->getQuery()
			        ->getResult(); 
	} 
}
