<?php

namespace GestionVentasBundle\Repository;

/**
 * ItemListaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemListaRepository extends \Doctrine\ORM\EntityRepository
{
}
