<?php

namespace GestionVentasBundle\Repository;

/**
 * ListaPrecioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ListaPrecioRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllLista() 
    {     
        return $this->createQueryBuilder('l')
                    ->where('l.activa = :activo')
                    ->setParameter('activo', true)
                    ->orderBy('l.codigo')
                    ->getQuery()
                    ->getResult(); 
    }
}
