<?php

namespace GestionVentasBundle\Repository;

/**
 * RemitoVentaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RemitoVentaRepository extends \Doctrine\ORM\EntityRepository
{
}
