<?php

namespace GestionFaenaBundle\Repository;

/**
 * AjusteMovimientoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AjusteMovimientoRepository extends \Doctrine\ORM\EntityRepository
{
}
