<?php

namespace GestionFaenaBundle\Repository;

/**
 * AtributoAbstractoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AtributoAbstractoRepository extends \Doctrine\ORM\EntityRepository
{
}
