<?php

namespace GestionFaenaBundle\Repository;

/**
 * ConceptoVentaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConceptoVentaRepository extends \Doctrine\ORM\EntityRepository
{
}
