<?php

namespace GestionFaenaBundle\Repository;

/**
 * GrupoMovimientosAutomaticoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GrupoMovimientosAutomaticoRepository extends \Doctrine\ORM\EntityRepository
{

	public function findAllMovimientosRealizadosProceso(\GestionFaenaBundle\Entity\faena\ProcesoFaenaDiaria $proceso,
											  			\GestionFaenaBundle\Entity\FaenaDiaria $faena) 
	{ 
        return $this->getEntityManager()
            		->createQuery('SELECT g 
	                               FROM GestionFaenaBundle:GrupoMovimientosAutomatico g 
	                               JOIN GestionFaenaBundle:PasoProceso pp WITH pp.grupoMovimiento = g
	                               JOIN GestionFaenaBundle:PasoProcesoRealizado ppr WITH ppr.paso = pp
	                               WHERE ppr.procesoFaenaDiaria = :proceso AND g.eliminado = :eliminado AND
	                               		 ppr.faenaDiaria = :faena
	                                GROUP BY g')
			        ->setParameter('proceso', $proceso)
			        ->setParameter('eliminado', false)
			        ->setParameter('faena', $faena)
			        ->getResult(); 
	}  

	public function getMovimientoWithAtributo(\GestionFaenaBundle\Entity\ProcesoFaena $proceso,
											  \GestionFaenaBundle\Entity\gestionBD\ArticuloAtributoConcepto $articulo) 
	{ 
	    return $this->createQueryBuilder('g')
	    			->join('g.automaticos', 'ma')
			        ->where('g.procesoFaena = :proceso')
			        ->andWhere('ma.articuloAtributoConcepto = :articulo')
			        ->setParameter('proceso', $proceso)
			        ->setParameter('articulo', $articulo)
			        ->getQuery()
			        ->getOneOrNullResult(); 
	}  
}
