<?php

namespace GestionFaenaBundle\Repository;

/**
 * PasoProcesoRealizadoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PasoProcesoRealizadoRepository extends \Doctrine\ORM\EntityRepository
{
	public function findPasoProcesoRealizado(\GestionFaenaBundle\Entity\faena\ProcesoFaenaDiaria $proceso,
											\GestionFaenaBundle\Entity\FaenaDiaria $faena,
											\GestionFaenaBundle\Entity\PasoProceso $paso) 
	{ 
	    return $this->createQueryBuilder('p')
			        ->where('p.procesoFaenaDiaria = :proceso')
			        ->andWhere('p.faenaDiaria = :faena')
			        ->andWhere('p.paso = :paso')
			        ->setParameter('proceso', $proceso)
			        ->setParameter('faena', $faena)
			        ->setParameter('paso', $paso)
			        ->getQuery()
			        ->getOneOrNullResult(); 
	}

	public function findPasosRealizadoProceso(\GestionFaenaBundle\Entity\faena\ProcesoFaenaDiaria $proceso,
											  \GestionFaenaBundle\Entity\FaenaDiaria $faena) 
	{ 
	    return $this->createQueryBuilder('p')
			        ->where('p.procesoFaenaDiaria = :proceso')
			        ->andWhere('p.faenaDiaria = :faena')
			        ->setParameter('proceso', $proceso)
			        ->setParameter('faena', $faena)
			        ->getQuery()
			        ->getResult(); 
	}  
}
