<?php

namespace GestionFaenaBundle\Repository;

/**
 * ProcesoInicioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProcesoInicioRepository extends \Doctrine\ORM\EntityRepository
{
}
