<?php

namespace GestionFaenaBundle\Repository;

/**
 * ProcesoMedioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProcesoMedioRepository extends \Doctrine\ORM\EntityRepository
{
}
