<?php

namespace GestionFaenaBundle\Repository;

/**
 * ProcesoFinRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProcesoFinRepository extends \Doctrine\ORM\EntityRepository
{
}
