<?php

namespace GestionFaenaBundle\Repository;

/**
 * ProcesoFaenaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProcesoFaenaRepository extends \Doctrine\ORM\EntityRepository
{

    public function findAllProcesos()
    {
        return $this->getEntityManager()
            		->createQuery('SELECT p FROM GestionFaenaBundle:ProcesoFaena p ORDER BY p.orden')
            		->getResult();
    }

    public function getProcesoInicio()
    {
        return $this->getEntityManager()
            		->createQuery('SELECT p FROM GestionFaenaBundle:ProcesoInicio p WHERE p.activo = :actvo')
            		->setParameter('actvo', true)
            		->getOneOrNullResult();
    }

    public function articlesOfProcess($proceso)
    {
        return $this->getEntityManager()
                    ->createQuery('SELECT apf
                                   FROM GestionFaenaBundle:gestionBD\ArticuloProcesoFaena apf
                                   WHERE apf.proceso = :proceso')
                    ->setParameter('proceso', $proceso)
                    ->getResult();
    }

    //Devuelve el proceso faena que admite imputar ventas (Gestion Camaras)
    public function getProcesoVenta()
    {
        return $this->createQueryBuilder('p')
                    ->where('p.permanente = :permanente')
                    ->andWhere('p.generaVentas = :genera')
                    ->andWhere('p.activo = :actvo')
                    ->setParameter('permanente', true)
                    ->setParameter('genera', true)
                    ->setParameter('actvo', true)
                    ->getQuery()
                    ->getOneOrNullResult(); 
    }
}
