<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'app.faena_controller' shared autowired service.

return $this->services['app.faena_controller'] = new \GestionFaenaBundle\Controller\GestionFaenaController();
