<?php

namespace GestionFaenaBundle\Repository\faena;

/**
 * AjusteStockRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AjusteStockRepository extends \Doctrine\ORM\EntityRepository
{
}
