<?php

namespace GestionFaenaBundle\Repository\faena;

/**
 * AtributoConceptoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AtributoConceptoRepository extends \Doctrine\ORM\EntityRepository
{
}
