<?php

namespace GestionFaenaBundle\Repository\faena;

/**
 * AtributoPorArticuloPorProcesoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AtributoPorArticuloPorProcesoRepository extends \Doctrine\ORM\EntityRepository
{
}
