<?php

namespace GestionFaenaBundle\Repository\faena;

/**
 * EntradaStockRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntradaStockRepository extends \Doctrine\ORM\EntityRepository
{
}
