<?php

namespace GestionFaenaBundle\Repository\faena;

/**
 * HorarioCargaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HorarioCargaRepository extends \Doctrine\ORM\EntityRepository
{
}
