<?php

namespace GestionFaenaBundle\Repository\faena;

/**
 * MovimientoAutomaticoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovimientoAutomaticoRepository extends \Doctrine\ORM\EntityRepository
{
}
