<?php

namespace GestionFaenaBundle\Repository\faena;

/**
 * MovimientoCompuestoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovimientoCompuestoRepository extends \Doctrine\ORM\EntityRepository
{
}
