<?php

namespace GestionFaenaBundle\Repository\faena;

/**
 * PropiedadAtributoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PropiedadAtributoRepository extends \Doctrine\ORM\EntityRepository
{
}
