<?php

namespace GestionFaenaBundle\Repository\faena;

/**
 * SalidaStockRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SalidaStockRepository extends \Doctrine\ORM\EntityRepository
{
}
