<?php

namespace GestionFaenaBundle\Repository\faena;

/**
 * TipoVentaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoVentaRepository extends \Doctrine\ORM\EntityRepository
{
}
