<?php

namespace GestionFaenaBundle\Repository\faena;

/**
 * TipoMovimientoConceptoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoMovimientoConceptoRepository extends \Doctrine\ORM\EntityRepository
{

    public function getTipoWithInstance($instance)
    {
        return $this->getEntityManager()
            		->createQuery('SELECT tm
            					   FROM GestionFaenaBundle:faena\TipoMovimientoConcepto tm
            					   WHERE tm.instancia = :instance')
                    ->setParameter('instance', $instance)
            		->getOneOrNullResult();
    }
}
