<?php

namespace GestionFaenaBundle\Repository\faena;

/**
 * TransformarTransferirStockRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransformarTransferirStockRepository extends \Doctrine\ORM\EntityRepository
{
}
