<?php

namespace GestionFaenaBundle\Repository\faena;

/**
 * TransferirStockRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransferirStockRepository extends \Doctrine\ORM\EntityRepository
{
}
