<?php

namespace GestionFaenaBundle\Repository\faena;

/**
 * TransformarStockRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransformarStockRepository extends \Doctrine\ORM\EntityRepository
{
}
