<?php

namespace GestionFaenaBundle\Repository\faena;

/**
 * ValorTextoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ValorTextoRepository extends \Doctrine\ORM\EntityRepository
{
}
