<?php

namespace GestionFaenaBundle\Repository\faena;

/**
 * ValorExternoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ValorExternoRepository extends \Doctrine\ORM\EntityRepository
{
}
