<?php

namespace GestionFaenaBundle\Repository\faena;

/**
 * ValorAtributoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ValorAtributoRepository extends \Doctrine\ORM\EntityRepository
{
}
