<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIjiaeav\appProdDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIjiaeav/appProdDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerIjiaeav.legacy');

    return;
}

if (!\class_exists(appProdDebugProjectContainer::class, false)) {
    \class_alias(\ContainerIjiaeav\appProdDebugProjectContainer::class, appProdDebugProjectContainer::class, false);
}

return new \ContainerIjiaeav\appProdDebugProjectContainer([
    'container.build_hash' => 'Ijiaeav',
    'container.build_id' => '7fcaf2d2',
    'container.build_time' => 1619103438,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIjiaeav');
