<?php

namespace Proxies\__CG__\GestionSigcerBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class GrupoSolicitud extends \GestionSigcerBundle\Entity\GrupoSolicitud implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'GestionSigcerBundle\\Entity\\GrupoSolicitud' . "\0" . 'id', '' . "\0" . 'GestionSigcerBundle\\Entity\\GrupoSolicitud' . "\0" . 'version', '' . "\0" . 'GestionSigcerBundle\\Entity\\GrupoSolicitud' . "\0" . 'codigoEstablecimiento', '' . "\0" . 'GestionSigcerBundle\\Entity\\GrupoSolicitud' . "\0" . 'roleEstablecimiento', '' . "\0" . 'GestionSigcerBundle\\Entity\\GrupoSolicitud' . "\0" . 'fecha', '' . "\0" . 'GestionSigcerBundle\\Entity\\GrupoSolicitud' . "\0" . 'paisDestino', '' . "\0" . 'GestionSigcerBundle\\Entity\\GrupoSolicitud' . "\0" . 'tropas', '' . "\0" . 'GestionSigcerBundle\\Entity\\GrupoSolicitud' . "\0" . 'solicitudes', '' . "\0" . 'GestionSigcerBundle\\Entity\\GrupoSolicitud' . "\0" . 'regionesGeneradas', '' . "\0" . 'GestionSigcerBundle\\Entity\\GrupoSolicitud' . "\0" . 'eliminada', '' . "\0" . 'GestionSigcerBundle\\Entity\\GrupoSolicitud' . "\0" . 'exportacion', '' . "\0" . 'GestionSigcerBundle\\Entity\\GrupoSolicitud' . "\0" . 'registroExportador'];
        }

        return ['__isInitialized__', '' . "\0" . 'GestionSigcerBundle\\Entity\\GrupoSolicitud' . "\0" . 'id', '' . "\0" . 'GestionSigcerBundle\\Entity\\GrupoSolicitud' . "\0" . 'version', '' . "\0" . 'GestionSigcerBundle\\Entity\\GrupoSolicitud' . "\0" . 'codigoEstablecimiento', '' . "\0" . 'GestionSigcerBundle\\Entity\\GrupoSolicitud' . "\0" . 'roleEstablecimiento', '' . "\0" . 'GestionSigcerBundle\\Entity\\GrupoSolicitud' . "\0" . 'fecha', '' . "\0" . 'GestionSigcerBundle\\Entity\\GrupoSolicitud' . "\0" . 'paisDestino', '' . "\0" . 'GestionSigcerBundle\\Entity\\GrupoSolicitud' . "\0" . 'tropas', '' . "\0" . 'GestionSigcerBundle\\Entity\\GrupoSolicitud' . "\0" . 'solicitudes', '' . "\0" . 'GestionSigcerBundle\\Entity\\GrupoSolicitud' . "\0" . 'regionesGeneradas', '' . "\0" . 'GestionSigcerBundle\\Entity\\GrupoSolicitud' . "\0" . 'eliminada', '' . "\0" . 'GestionSigcerBundle\\Entity\\GrupoSolicitud' . "\0" . 'exportacion', '' . "\0" . 'GestionSigcerBundle\\Entity\\GrupoSolicitud' . "\0" . 'registroExportador'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (GrupoSolicitud $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getTropa()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTropa', []);

        return parent::getTropa();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function setVersion($version)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVersion', [$version]);

        return parent::setVersion($version);
    }

    /**
     * {@inheritDoc}
     */
    public function getVersion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVersion', []);

        return parent::getVersion();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodigoEstablecimiento($codigoEstablecimiento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodigoEstablecimiento', [$codigoEstablecimiento]);

        return parent::setCodigoEstablecimiento($codigoEstablecimiento);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodigoEstablecimiento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodigoEstablecimiento', []);

        return parent::getCodigoEstablecimiento();
    }

    /**
     * {@inheritDoc}
     */
    public function setRoleEstablecimiento($roleEstablecimiento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRoleEstablecimiento', [$roleEstablecimiento]);

        return parent::setRoleEstablecimiento($roleEstablecimiento);
    }

    /**
     * {@inheritDoc}
     */
    public function getRoleEstablecimiento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRoleEstablecimiento', []);

        return parent::getRoleEstablecimiento();
    }

    /**
     * {@inheritDoc}
     */
    public function setFecha($fecha)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFecha', [$fecha]);

        return parent::setFecha($fecha);
    }

    /**
     * {@inheritDoc}
     */
    public function getFecha()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFecha', []);

        return parent::getFecha();
    }

    /**
     * {@inheritDoc}
     */
    public function setPaisDestino(\GestionSigcerBundle\Entity\opciones\PaisDestino $paisDestino = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPaisDestino', [$paisDestino]);

        return parent::setPaisDestino($paisDestino);
    }

    /**
     * {@inheritDoc}
     */
    public function getPaisDestino()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaisDestino', []);

        return parent::getPaisDestino();
    }

    /**
     * {@inheritDoc}
     */
    public function addTropa(\GestionSigcerBundle\Entity\TropaSolicitud $tropa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addTropa', [$tropa]);

        return parent::addTropa($tropa);
    }

    /**
     * {@inheritDoc}
     */
    public function removeTropa(\GestionSigcerBundle\Entity\TropaSolicitud $tropa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeTropa', [$tropa]);

        return parent::removeTropa($tropa);
    }

    /**
     * {@inheritDoc}
     */
    public function getTropas()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTropas', []);

        return parent::getTropas();
    }

    /**
     * {@inheritDoc}
     */
    public function addSolicitude(\GestionSigcerBundle\Entity\Solicitud $solicitude)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addSolicitude', [$solicitude]);

        return parent::addSolicitude($solicitude);
    }

    /**
     * {@inheritDoc}
     */
    public function removeSolicitude(\GestionSigcerBundle\Entity\Solicitud $solicitude)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeSolicitude', [$solicitude]);

        return parent::removeSolicitude($solicitude);
    }

    /**
     * {@inheritDoc}
     */
    public function getSolicitudes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSolicitudes', []);

        return parent::getSolicitudes();
    }

    /**
     * {@inheritDoc}
     */
    public function addRegionesGenerada(\GestionSigcerBundle\Entity\opciones\Region $regionesGenerada)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addRegionesGenerada', [$regionesGenerada]);

        return parent::addRegionesGenerada($regionesGenerada);
    }

    /**
     * {@inheritDoc}
     */
    public function removeRegionesGenerada(\GestionSigcerBundle\Entity\opciones\Region $regionesGenerada)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeRegionesGenerada', [$regionesGenerada]);

        return parent::removeRegionesGenerada($regionesGenerada);
    }

    /**
     * {@inheritDoc}
     */
    public function getRegionesGeneradas()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRegionesGeneradas', []);

        return parent::getRegionesGeneradas();
    }

    /**
     * {@inheritDoc}
     */
    public function generoSolicitudes(\GestionSigcerBundle\Entity\opciones\Region $region)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'generoSolicitudes', [$region]);

        return parent::generoSolicitudes($region);
    }

    /**
     * {@inheritDoc}
     */
    public function setEliminada($eliminada)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEliminada', [$eliminada]);

        return parent::setEliminada($eliminada);
    }

    /**
     * {@inheritDoc}
     */
    public function getEliminada()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEliminada', []);

        return parent::getEliminada();
    }

    /**
     * {@inheritDoc}
     */
    public function setExportacion($exportacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExportacion', [$exportacion]);

        return parent::setExportacion($exportacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getExportacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExportacion', []);

        return parent::getExportacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setRegistroExportador($registroExportador)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRegistroExportador', [$registroExportador]);

        return parent::setRegistroExportador($registroExportador);
    }

    /**
     * {@inheritDoc}
     */
    public function getRegistroExportador()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRegistroExportador', []);

        return parent::getRegistroExportador();
    }

}
