<?php

namespace Proxies\__CG__\GestionFaenaBundle\Entity\faena;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ProcesoFaenaDiaria extends \GestionFaenaBundle\Entity\faena\ProcesoFaenaDiaria implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'GestionFaenaBundle\\Entity\\faena\\ProcesoFaenaDiaria' . "\0" . 'id', '' . "\0" . 'GestionFaenaBundle\\Entity\\faena\\ProcesoFaenaDiaria' . "\0" . 'procesoFaena', '' . "\0" . 'GestionFaenaBundle\\Entity\\faena\\ProcesoFaenaDiaria' . "\0" . 'ultimoMovimiento', '' . "\0" . 'GestionFaenaBundle\\Entity\\faena\\ProcesoFaenaDiaria' . "\0" . 'movimientos', '' . "\0" . 'GestionFaenaBundle\\Entity\\faena\\ProcesoFaenaDiaria' . "\0" . 'movimientosRealizados', '' . "\0" . 'GestionFaenaBundle\\Entity\\faena\\ProcesoFaenaDiaria' . "\0" . 'pesoPromedio'];
        }

        return ['__isInitialized__', '' . "\0" . 'GestionFaenaBundle\\Entity\\faena\\ProcesoFaenaDiaria' . "\0" . 'id', '' . "\0" . 'GestionFaenaBundle\\Entity\\faena\\ProcesoFaenaDiaria' . "\0" . 'procesoFaena', '' . "\0" . 'GestionFaenaBundle\\Entity\\faena\\ProcesoFaenaDiaria' . "\0" . 'ultimoMovimiento', '' . "\0" . 'GestionFaenaBundle\\Entity\\faena\\ProcesoFaenaDiaria' . "\0" . 'movimientos', '' . "\0" . 'GestionFaenaBundle\\Entity\\faena\\ProcesoFaenaDiaria' . "\0" . 'movimientosRealizados', '' . "\0" . 'GestionFaenaBundle\\Entity\\faena\\ProcesoFaenaDiaria' . "\0" . 'pesoPromedio'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (ProcesoFaenaDiaria $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function setProcesoFaena(\GestionFaenaBundle\Entity\ProcesoFaena $procesoFaena = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProcesoFaena', [$procesoFaena]);

        return parent::setProcesoFaena($procesoFaena);
    }

    /**
     * {@inheritDoc}
     */
    public function getProcesoFaena()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProcesoFaena', []);

        return parent::getProcesoFaena();
    }

    /**
     * {@inheritDoc}
     */
    public function setUltimoMovimiento($ultimoMovimiento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUltimoMovimiento', [$ultimoMovimiento]);

        return parent::setUltimoMovimiento($ultimoMovimiento);
    }

    /**
     * {@inheritDoc}
     */
    public function getUltimoMovimiento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUltimoMovimiento', []);

        return parent::getUltimoMovimiento();
    }

    /**
     * {@inheritDoc}
     */
    public function updateActionPre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'updateActionPre', []);

        return parent::updateActionPre();
    }

    /**
     * {@inheritDoc}
     */
    public function addMovimiento(\GestionFaenaBundle\Entity\faena\MovimientoStock $movimiento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addMovimiento', [$movimiento]);

        return parent::addMovimiento($movimiento);
    }

    /**
     * {@inheritDoc}
     */
    public function removeMovimiento(\GestionFaenaBundle\Entity\faena\MovimientoStock $movimiento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeMovimiento', [$movimiento]);

        return parent::removeMovimiento($movimiento);
    }

    /**
     * {@inheritDoc}
     */
    public function getMovimientos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMovimientos', []);

        return parent::getMovimientos();
    }

    /**
     * {@inheritDoc}
     */
    public function getStockArticulo(\GestionFaenaBundle\Entity\FaenaDiaria $faena, \GestionFaenaBundle\Entity\gestionBD\Articulo $articulo, \GestionFaenaBundle\Entity\gestionBD\AtributoAbstracto $atributo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStockArticulo', [$faena, $articulo, $atributo]);

        return parent::getStockArticulo($faena, $articulo, $atributo);
    }

    /**
     * {@inheritDoc}
     */
    public function getStockArticuloConFaenaDiaria(\GestionFaenaBundle\Entity\FaenaDiaria $faena, \GestionFaenaBundle\Entity\gestionBD\Articulo $articulo, \GestionFaenaBundle\Entity\gestionBD\AtributoAbstracto $atributo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStockArticuloConFaenaDiaria', [$faena, $articulo, $atributo]);

        return parent::getStockArticuloConFaenaDiaria($faena, $articulo, $atributo);
    }

    /**
     * {@inheritDoc}
     */
    public function getMovimientosArticulo(\GestionFaenaBundle\Entity\gestionBD\Articulo $articulo, \GestionFaenaBundle\Entity\FaenaDiaria $faena = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMovimientosArticulo', [$articulo, $faena]);

        return parent::getMovimientosArticulo($articulo, $faena);
    }

    /**
     * {@inheritDoc}
     */
    public function getAllMovimientosArticulo(\GestionFaenaBundle\Entity\gestionBD\Articulo $articulo, \GestionFaenaBundle\Entity\FaenaDiaria $faena = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAllMovimientosArticulo', [$articulo, $faena]);

        return parent::getAllMovimientosArticulo($articulo, $faena);
    }

    /**
     * {@inheritDoc}
     */
    public function getStockArticuloConAtributo(\GestionFaenaBundle\Entity\gestionBD\Articulo $articulo, \GestionFaenaBundle\Entity\gestionBD\AtributoAbstracto $atributo, $soloIngreso, $accion, \GestionFaenaBundle\Entity\gestionBD\FactorCalculo $factor = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStockArticuloConAtributo', [$articulo, $atributo, $soloIngreso, $accion, $factor]);

        return parent::getStockArticuloConAtributo($articulo, $atributo, $soloIngreso, $accion, $factor);
    }

    /**
     * {@inheritDoc}
     */
    public function realizoMovimientoConArticuloAtriutoConcepto(\GestionFaenaBundle\Entity\gestionBD\ArticuloAtributoConcepto $artAtrCon)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'realizoMovimientoConArticuloAtriutoConcepto', [$artAtrCon]);

        return parent::realizoMovimientoConArticuloAtriutoConcepto($artAtrCon);
    }

    /**
     * {@inheritDoc}
     */
    public function setPesoPromedio($pesoPromedio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPesoPromedio', [$pesoPromedio]);

        return parent::setPesoPromedio($pesoPromedio);
    }

    /**
     * {@inheritDoc}
     */
    public function getPesoPromedio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPesoPromedio', []);

        return parent::getPesoPromedio();
    }

    /**
     * {@inheritDoc}
     */
    public function addMovimientosRealizado(\GestionFaenaBundle\Entity\ProcesoFaena $movimientosRealizado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addMovimientosRealizado', [$movimientosRealizado]);

        return parent::addMovimientosRealizado($movimientosRealizado);
    }

    /**
     * {@inheritDoc}
     */
    public function removeMovimientosRealizado(\GestionFaenaBundle\Entity\ProcesoFaena $movimientosRealizado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeMovimientosRealizado', [$movimientosRealizado]);

        return parent::removeMovimientosRealizado($movimientosRealizado);
    }

    /**
     * {@inheritDoc}
     */
    public function getMovimientosRealizados()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMovimientosRealizados', []);

        return parent::getMovimientosRealizados();
    }

}
