<?php

namespace Proxies\__CG__\GestionFaenaBundle\Entity\gestionBD;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class RubroEntidad extends \GestionFaenaBundle\Entity\gestionBD\RubroEntidad implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'GestionFaenaBundle\\Entity\\gestionBD\\RubroEntidad' . "\0" . 'id', '' . "\0" . 'GestionFaenaBundle\\Entity\\gestionBD\\RubroEntidad' . "\0" . 'rubro', '' . "\0" . 'GestionFaenaBundle\\Entity\\gestionBD\\RubroEntidad' . "\0" . 'activo', '' . "\0" . 'GestionFaenaBundle\\Entity\\gestionBD\\RubroEntidad' . "\0" . 'entidades'];
        }

        return ['__isInitialized__', '' . "\0" . 'GestionFaenaBundle\\Entity\\gestionBD\\RubroEntidad' . "\0" . 'id', '' . "\0" . 'GestionFaenaBundle\\Entity\\gestionBD\\RubroEntidad' . "\0" . 'rubro', '' . "\0" . 'GestionFaenaBundle\\Entity\\gestionBD\\RubroEntidad' . "\0" . 'activo', '' . "\0" . 'GestionFaenaBundle\\Entity\\gestionBD\\RubroEntidad' . "\0" . 'entidades'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (RubroEntidad $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setRubro($rubro)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRubro', [$rubro]);

        return parent::setRubro($rubro);
    }

    /**
     * {@inheritDoc}
     */
    public function getRubro()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRubro', []);

        return parent::getRubro();
    }

    /**
     * {@inheritDoc}
     */
    public function setActivo($activo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActivo', [$activo]);

        return parent::setActivo($activo);
    }

    /**
     * {@inheritDoc}
     */
    public function getActivo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActivo', []);

        return parent::getActivo();
    }

    /**
     * {@inheritDoc}
     */
    public function addEntidade(\GestionFaenaBundle\Entity\gestionBD\EntidadExterna $entidade)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addEntidade', [$entidade]);

        return parent::addEntidade($entidade);
    }

    /**
     * {@inheritDoc}
     */
    public function removeEntidade(\GestionFaenaBundle\Entity\gestionBD\EntidadExterna $entidade)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeEntidade', [$entidade]);

        return parent::removeEntidade($entidade);
    }

    /**
     * {@inheritDoc}
     */
    public function getEntidades()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEntidades', []);

        return parent::getEntidades();
    }

}
