<?php

namespace Proxies\__CG__\GestionFaenaBundle\Entity\faena;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ValorExterno extends \GestionFaenaBundle\Entity\faena\ValorExterno implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'GestionFaenaBundle\\Entity\\faena\\ValorExterno' . "\0" . 'entidadExterna'];
        }

        return ['__isInitialized__', '' . "\0" . 'GestionFaenaBundle\\Entity\\faena\\ValorExterno' . "\0" . 'entidadExterna'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (ValorExterno $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getDataValue()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataValue', []);

        return parent::getDataValue();
    }

    /**
     * {@inheritDoc}
     */
    public function setEntidadExterna(\GestionFaenaBundle\Entity\gestionBD\EntidadExterna $entidadExterna = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEntidadExterna', [$entidadExterna]);

        return parent::setEntidadExterna($entidadExterna);
    }

    /**
     * {@inheritDoc}
     */
    public function getEntidadExterna()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEntidadExterna', []);

        return parent::getEntidadExterna();
    }

    /**
     * {@inheritDoc}
     */
    public function calcularValor($movimiento, $entityManager, $automatico = false)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'calcularValor', [$movimiento, $entityManager, $automatico]);

        return parent::calcularValor($movimiento, $entityManager, $automatico);
    }

    /**
     * {@inheritDoc}
     */
    public function getData()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getData', []);

        return parent::getData();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function isValid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isValid', []);

        return parent::isValid();
    }

    /**
     * {@inheritDoc}
     */
    public function isNumeric()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isNumeric', []);

        return parent::isNumeric();
    }

    /**
     * {@inheritDoc}
     */
    public function updateAtributoAbstracto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'updateAtributoAbstracto', []);

        return parent::updateAtributoAbstracto();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setMovimiento(\GestionFaenaBundle\Entity\faena\MovimientoStock $movimiento = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMovimiento', [$movimiento]);

        return parent::setMovimiento($movimiento);
    }

    /**
     * {@inheritDoc}
     */
    public function getMovimiento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMovimiento', []);

        return parent::getMovimiento();
    }

    /**
     * {@inheritDoc}
     */
    public function setAtributo(\GestionFaenaBundle\Entity\gestionBD\Atributo $atributo = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAtributo', [$atributo]);

        return parent::setAtributo($atributo);
    }

    /**
     * {@inheritDoc}
     */
    public function getAtributo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAtributo', []);

        return parent::getAtributo();
    }

    /**
     * {@inheritDoc}
     */
    public function setAtributoAbstracto(\GestionFaenaBundle\Entity\gestionBD\AtributoAbstracto $atributoAbstracto = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAtributoAbstracto', [$atributoAbstracto]);

        return parent::setAtributoAbstracto($atributoAbstracto);
    }

    /**
     * {@inheritDoc}
     */
    public function getAtributoAbstracto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAtributoAbstracto', []);

        return parent::getAtributoAbstracto();
    }

    /**
     * {@inheritDoc}
     */
    public function setPosicion($posicion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPosicion', [$posicion]);

        return parent::setPosicion($posicion);
    }

    /**
     * {@inheritDoc}
     */
    public function getPosicion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPosicion', []);

        return parent::getPosicion();
    }

    /**
     * {@inheritDoc}
     */
    public function setMostrar($mostrar)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMostrar', [$mostrar]);

        return parent::setMostrar($mostrar);
    }

    /**
     * {@inheritDoc}
     */
    public function getMostrar()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMostrar', []);

        return parent::getMostrar();
    }

    /**
     * {@inheritDoc}
     */
    public function setFaenaDiaria(\GestionFaenaBundle\Entity\FaenaDiaria $faenaDiaria = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFaenaDiaria', [$faenaDiaria]);

        return parent::setFaenaDiaria($faenaDiaria);
    }

    /**
     * {@inheritDoc}
     */
    public function getFaenaDiaria()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFaenaDiaria', []);

        return parent::getFaenaDiaria();
    }

}
