<?php

namespace Proxies\__CG__\GestionFaenaBundle\Entity\exportacion;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class TipoPallet extends \GestionFaenaBundle\Entity\exportacion\TipoPallet implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'GestionFaenaBundle\\Entity\\exportacion\\TipoPallet' . "\0" . 'id', '' . "\0" . 'GestionFaenaBundle\\Entity\\exportacion\\TipoPallet' . "\0" . 'prefijo', '' . "\0" . 'GestionFaenaBundle\\Entity\\exportacion\\TipoPallet' . "\0" . 'tipo', '' . "\0" . 'GestionFaenaBundle\\Entity\\exportacion\\TipoPallet' . "\0" . 'capacidad', '' . "\0" . 'GestionFaenaBundle\\Entity\\exportacion\\TipoPallet' . "\0" . 'articulos', '' . "\0" . 'GestionFaenaBundle\\Entity\\exportacion\\TipoPallet' . "\0" . 'activo'];
        }

        return ['__isInitialized__', '' . "\0" . 'GestionFaenaBundle\\Entity\\exportacion\\TipoPallet' . "\0" . 'id', '' . "\0" . 'GestionFaenaBundle\\Entity\\exportacion\\TipoPallet' . "\0" . 'prefijo', '' . "\0" . 'GestionFaenaBundle\\Entity\\exportacion\\TipoPallet' . "\0" . 'tipo', '' . "\0" . 'GestionFaenaBundle\\Entity\\exportacion\\TipoPallet' . "\0" . 'capacidad', '' . "\0" . 'GestionFaenaBundle\\Entity\\exportacion\\TipoPallet' . "\0" . 'articulos', '' . "\0" . 'GestionFaenaBundle\\Entity\\exportacion\\TipoPallet' . "\0" . 'activo'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (TipoPallet $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipo($tipo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipo', [$tipo]);

        return parent::setTipo($tipo);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipo', []);

        return parent::getTipo();
    }

    /**
     * {@inheritDoc}
     */
    public function setCapacidad($capacidad)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCapacidad', [$capacidad]);

        return parent::setCapacidad($capacidad);
    }

    /**
     * {@inheritDoc}
     */
    public function getCapacidad()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCapacidad', []);

        return parent::getCapacidad();
    }

    /**
     * {@inheritDoc}
     */
    public function addArticulo(\GestionFaenaBundle\Entity\gestionBD\Articulo $articulo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addArticulo', [$articulo]);

        return parent::addArticulo($articulo);
    }

    /**
     * {@inheritDoc}
     */
    public function removeArticulo(\GestionFaenaBundle\Entity\gestionBD\Articulo $articulo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeArticulo', [$articulo]);

        return parent::removeArticulo($articulo);
    }

    /**
     * {@inheritDoc}
     */
    public function getArticulos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArticulos', []);

        return parent::getArticulos();
    }

    /**
     * {@inheritDoc}
     */
    public function setActivo($activo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActivo', [$activo]);

        return parent::setActivo($activo);
    }

    /**
     * {@inheritDoc}
     */
    public function getActivo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActivo', []);

        return parent::getActivo();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrefijo($prefijo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrefijo', [$prefijo]);

        return parent::setPrefijo($prefijo);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrefijo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrefijo', []);

        return parent::getPrefijo();
    }

}
