<?php

namespace Proxies\__CG__\GestionFaenaBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class FaenaDiaria extends \GestionFaenaBundle\Entity\FaenaDiaria implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'GestionFaenaBundle\\Entity\\FaenaDiaria' . "\0" . 'id', '' . "\0" . 'GestionFaenaBundle\\Entity\\FaenaDiaria' . "\0" . 'fechaFaena', '' . "\0" . 'GestionFaenaBundle\\Entity\\FaenaDiaria' . "\0" . 'isActive', '' . "\0" . 'GestionFaenaBundle\\Entity\\FaenaDiaria' . "\0" . 'fechaAlta', '' . "\0" . 'GestionFaenaBundle\\Entity\\FaenaDiaria' . "\0" . 'fechaCierre', '' . "\0" . 'GestionFaenaBundle\\Entity\\FaenaDiaria' . "\0" . 'finalizada', '' . "\0" . 'GestionFaenaBundle\\Entity\\FaenaDiaria' . "\0" . 'procesos', '' . "\0" . 'GestionFaenaBundle\\Entity\\FaenaDiaria' . "\0" . 'userCreate', '' . "\0" . 'GestionFaenaBundle\\Entity\\FaenaDiaria' . "\0" . 'userClose'];
        }

        return ['__isInitialized__', '' . "\0" . 'GestionFaenaBundle\\Entity\\FaenaDiaria' . "\0" . 'id', '' . "\0" . 'GestionFaenaBundle\\Entity\\FaenaDiaria' . "\0" . 'fechaFaena', '' . "\0" . 'GestionFaenaBundle\\Entity\\FaenaDiaria' . "\0" . 'isActive', '' . "\0" . 'GestionFaenaBundle\\Entity\\FaenaDiaria' . "\0" . 'fechaAlta', '' . "\0" . 'GestionFaenaBundle\\Entity\\FaenaDiaria' . "\0" . 'fechaCierre', '' . "\0" . 'GestionFaenaBundle\\Entity\\FaenaDiaria' . "\0" . 'finalizada', '' . "\0" . 'GestionFaenaBundle\\Entity\\FaenaDiaria' . "\0" . 'procesos', '' . "\0" . 'GestionFaenaBundle\\Entity\\FaenaDiaria' . "\0" . 'userCreate', '' . "\0" . 'GestionFaenaBundle\\Entity\\FaenaDiaria' . "\0" . 'userClose'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (FaenaDiaria $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getValuesForCalculo(\GestionFaenaBundle\Entity\opciones\CalculoFaena $calculo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getValuesForCalculo', [$calculo]);

        return parent::getValuesForCalculo($calculo);
    }

    /**
     * {@inheritDoc}
     */
    public function getProceso($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProceso', [$id]);

        return parent::getProceso($id);
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAtValue()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAtValue', []);

        return parent::setCreatedAtValue();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaFaena($fechaFaena)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaFaena', [$fechaFaena]);

        return parent::setFechaFaena($fechaFaena);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaFaena()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaFaena', []);

        return parent::getFechaFaena();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsActive($isActive)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsActive', [$isActive]);

        return parent::setIsActive($isActive);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsActive()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsActive', []);

        return parent::getIsActive();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaAlta($fechaAlta)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaAlta', [$fechaAlta]);

        return parent::setFechaAlta($fechaAlta);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaAlta()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaAlta', []);

        return parent::getFechaAlta();
    }

    /**
     * {@inheritDoc}
     */
    public function addProceso(\GestionFaenaBundle\Entity\faena\ProcesoFaenaDiaria $proceso)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addProceso', [$proceso]);

        return parent::addProceso($proceso);
    }

    /**
     * {@inheritDoc}
     */
    public function removeProceso(\GestionFaenaBundle\Entity\faena\ProcesoFaenaDiaria $proceso)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeProceso', [$proceso]);

        return parent::removeProceso($proceso);
    }

    /**
     * {@inheritDoc}
     */
    public function getProcesos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProcesos', []);

        return parent::getProcesos();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function setFinalizada($finalizada)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFinalizada', [$finalizada]);

        return parent::setFinalizada($finalizada);
    }

    /**
     * {@inheritDoc}
     */
    public function getFinalizada()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFinalizada', []);

        return parent::getFinalizada();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserCreate(\AppBundle\Entity\User $userCreate = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserCreate', [$userCreate]);

        return parent::setUserCreate($userCreate);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserCreate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserCreate', []);

        return parent::getUserCreate();
    }

    /**
     * {@inheritDoc}
     */
    public function getState()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getState', []);

        return parent::getState();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaCierre($fechaCierre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaCierre', [$fechaCierre]);

        return parent::setFechaCierre($fechaCierre);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaCierre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaCierre', []);

        return parent::getFechaCierre();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserClose(\AppBundle\Entity\User $userClose = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserClose', [$userClose]);

        return parent::setUserClose($userClose);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserClose()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserClose', []);

        return parent::getUserClose();
    }

    /**
     * {@inheritDoc}
     */
    public function faenaSinMovimientos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'faenaSinMovimientos', []);

        return parent::faenaSinMovimientos();
    }

    /**
     * {@inheritDoc}
     */
    public function getProcesosDestinos(\GestionFaenaBundle\Entity\ProcesoFaena $proceso)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProcesosDestinos', [$proceso]);

        return parent::getProcesosDestinos($proceso);
    }

}
