<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'app.fpdf' shared autowired service.

include_once $this->targetDirs[3].'\\src\\GestionFaenaBundle\\Services\\fpdf\\FPDF.php';

return $this->services['app.fpdf'] = new \GestionFaenaBundle\Services\fpdf\FPDF('null');
