<?php

namespace GestionVentasBundle\Repository\options;

/**
 * EntidadExternaConceptoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntidadExternaConceptoRepository extends \Doctrine\ORM\EntityRepository
{

    //Devuelve la entidad externa concepto correspondiente a los parametros de clase y proceso
    public function getEntidadOfClass($class, \GestionFaenaBundle\Entity\ProcesoFaena $proceso)
    {
	    return $this->createQueryBuilder('e')
			        ->where('e.entidad = :entidad')
			        ->andWhere('e.proceso = :proceso')
			        ->setParameter('entidad', $class)
			        ->setParameter('proceso', $proceso)
			        ->getQuery()
                    ->getOneOrNullResult();
    }
}
