<?php

namespace GestionVentasBundle\Repository\options;

/**
 * OpcionVentaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OpcionVentaRepository extends \Doctrine\ORM\EntityRepository
{
}
