<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'app.pdf' shared autowired service.

include_once $this->targetDirs[3].'\\src\\GestionFaenaBundle\\Services\\fpdf\\FPDF.php';
include_once $this->targetDirs[3].'\\src\\GestionFaenaBundle\\Services\\fpdf\\PDF.php';

return $this->services['app.pdf'] = new \GestionFaenaBundle\Services\fpdf\PDF('null');
