<?php

namespace GestionSigcerBundle\Repository;

/**
 * SolicitudRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SolicitudRepository extends \Doctrine\ORM\EntityRepository
{
	public function findSolicitudes(\GestionSigcerBundle\Entity\GrupoSolicitud $grupo,
									\GestionSigcerBundle\Entity\opciones\Region $region) 
	{ 
	    return $this->createQueryBuilder('s')
	    			->join('s.zona', 'z')
	    			->where('z.region = :region AND s.grupo = :grupo')
	    			->setParameter('region', $region)
	    			->setParameter('grupo', $grupo)
			        ->addOrderBy('z.codigo')
			        ->getQuery()
			        ->getResult(); 
	} 

	public function findSolicitudesWihtPrecinto($precinto) 
	{ 
	    $query =  $this->createQueryBuilder('s')
		    			->andWhere('s.precintoSenasa LIKE :numero')
		    			->setParameter('numero', '%'.$precinto.'%')
				        ->getQuery()
				        ->getResult();
		return $query;

		$query = $this->getEntityManager()->createQuery("SELECT s FROM GestionSigcerBundle:Solicitud s WHERE s.precintoSenasa LIKE :foo");
		$query->setParameter('foo', '%'.$precinto.'%');
		$users = $query->getResult();		
		return $users;
		return array(
        'sql'        => $query->getSQL(),
        'parameters' => $query->getParameters(),
        );
	} 
}
