<?php

namespace GestionSigcerBundle\Repository;

/**
 * TropaSolicitudRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TropaSolicitudRepository extends \Doctrine\ORM\EntityRepository
{

	public function findTropaWithLote(\GestionSigcerBundle\Entity\GrupoSolicitud $grupo, $lote) 
	{ 
	    return $this->createQueryBuilder('t')
	    			->where('t.grupoSolicitud = :grupo AND t.lote = :lote')
	    			->setParameter('grupo', $grupo)
	    			->setParameter('lote', $lote)
			        ->getQuery()
			        ->getOneOrNullResult(); 
	} 
}
