<?php

namespace GestionFaenaBundle\Repository\exportacion;

/**
 * PalletFaenaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PalletFaenaRepository extends \Doctrine\ORM\EntityRepository
{
	public function existePalletAbierto(\GestionFaenaBundle\Entity\exportacion\TipoPallet $tipo, $codigo) 
	{ 
	    return $this->createQueryBuilder('p')
			        ->where('p.codigo = :codigo')
			        ->andWhere('p.tipoPallet = :tipoPallet')
			        ->andWhere('p.eliminado = :eliminado')
			        ->setParameter('codigo', $codigo)
			        ->setParameter('tipoPallet', $tipo)
			        ->setParameter('eliminado', false)
			        ->getQuery()
			        ->getOneOrNullResult();  
	} 

	public function getPalletsActivos() 
	{ 
	    return $this->createQueryBuilder('p')
			        ->where('p.completo = :completo')
			        ->andWhere('p.eliminado = :eliminado')
			        ->setParameter('completo', false)
			        ->setParameter('eliminado', false)
			        ->getQuery()
			        ->getResult();  
	} 
}
