<?php

namespace GestionFaenaBundle\Repository\gestionBD;

/**
 * ArticuloProcesoFaenaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticuloProcesoFaenaRepository extends \Doctrine\ORM\EntityRepository
{
}
