<?php

namespace GestionFaenaBundle\Repository\gestionBD;

/**
 * ArticuloRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticuloRepository extends \Doctrine\ORM\EntityRepository
{

	public function getListaArticulos() 
	{ 
        return $this->getEntityManager()
            		->createQuery('SELECT a
            					   FROM GestionFaenaBundle:gestionBD\Articulo a 
            					   LEFT JOIN a.categoria c
                                   LEFT JOIN a.subcategoria s
            					   WHERE a.eliminado = :eliminado
            					   ORDER BY c.orden, s.orden, a.orden, a.id')
            		->setParameter('eliminado', false)
            		->getResult();
	} 

    public function getListaArticulosConCategoria() 
    { 
        return $this->getEntityManager()
                    ->createQuery('SELECT a
                                   FROM GestionFaenaBundle:gestionBD\Articulo a 
                                   JOIN a.categoria c
                                   JOIN a.subcategoria s
                                   WHERE a.eliminado = :eliminado
                                   ORDER BY c.orden, s.orden, a.orden, a.id')
                    ->setParameter('eliminado', false)
                    ->getResult();
    } 

    public function getArticulosConCodigos($codigos) 
    { 
        return $this->getEntityManager()
                    ->createQuery('SELECT a
                                   FROM GestionFaenaBundle:gestionBD\Articulo a 
                                   WHERE a.codigoInterno IN (:codigos)')
                    ->setParameter('codigos', $codigos)
                    ->getResult();
    } 

    public function getArticuloConCodigo($codigo) 
    { 
        return $this->getEntityManager()
                    ->createQuery('SELECT a
                                   FROM GestionFaenaBundle:gestionBD\Articulo a 
                                   WHERE a.codigoInterno = :codigo')
                    ->setParameter('codigo', $codigo)
                    ->getOneOrNullResult();
    } 

    public function getArticulosAClasificar(\GestionFaenaBundle\Entity\gestionBD\Articulo $articuloBase) 
    { 
        return $this->getEntityManager()
                    ->createQuery('SELECT a.id as idArticulo, 
                                          a.nombreResumido as articulo,
                                          c.id as idCategoria,
                                          c.categoria as categoria,
                                          s.id as idSubcategoria,
                                          s.subcategoria as subcategoria
                                   FROM GestionFaenaBundle:gestionBD\Articulo a 
                                   JOIN a.categoria c
                                   JOIN a.subcategoria s
                                   WHERE a.articuloBase = :articuloBase AND a.eliminado = :eliminado
                                   ORDER BY c.orden, s.orden, a.orden, a.id')
                    ->setParameter('articuloBase', $articuloBase)
                    ->setParameter('eliminado', false)
                    ->getResult();
    } 
}
