<?php

namespace GestionFaenaBundle\Repository\gestionBD;

/**
 * AtributoMedibleManualRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AtributoMedibleManualRepository extends \Doctrine\ORM\EntityRepository
{
}
