<?php

namespace GestionFaenaBundle\Repository\gestionBD;

/**
 * AtributoInformableExternoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AtributoInformableExternoRepository extends \Doctrine\ORM\EntityRepository
{
}
