<?php

namespace GestionFaenaBundle\Repository\gestionBD;

/**
 * AtributoMedibleAutomaticoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AtributoMedibleAutomaticoRepository extends \Doctrine\ORM\EntityRepository
{
}
