<?php

namespace GestionFaenaBundle\Repository\gestionBD;

/**
 * AtributoMedibleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AtributoMedibleRepository extends \Doctrine\ORM\EntityRepository
{
}
