<?php

namespace GestionFaenaBundle\Repository\gestionBD;

/**
 * AtributoProcesoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AtributoProcesoRepository extends \Doctrine\ORM\EntityRepository
{
}
