<?php

namespace GestionFaenaBundle\Repository\gestionBD;

/**
 * AtributoInformableRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AtributoInformableRepository extends \Doctrine\ORM\EntityRepository
{
}
