<?php

namespace GestionFaenaBundle\Repository\gestionBD;

/**
 * AtributoInformableArbitrarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AtributoInformableArbitrarioRepository extends \Doctrine\ORM\EntityRepository
{
}
