<?php

namespace GestionFaenaBundle\Repository\gestionBD;

/**
 * CamionVentaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CamionVentaRepository extends \Doctrine\ORM\EntityRepository
{
}
