<?php

namespace GestionFaenaBundle\Repository\gestionBD;

/**
 * CargadorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CargadorRepository extends \Doctrine\ORM\EntityRepository
{
}
