<?php

namespace GestionFaenaBundle\Repository\gestionBD;

/**
 * CategoriaArticuloRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoriaArticuloRepository extends \Doctrine\ORM\EntityRepository
{
}
