<?php

namespace GestionFaenaBundle\Repository\gestionBD;

/**
 * EmpresaTransporteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmpresaTransporteRepository extends \Doctrine\ORM\EntityRepository
{
}
