<?php

namespace GestionFaenaBundle\Repository\gestionBD;

/**
 * EntidadComercialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntidadComercialRepository extends \Doctrine\ORM\EntityRepository
{
}
