<?php

namespace GestionFaenaBundle\Repository\gestionBD;

/**
 * GranjaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GranjaRepository extends \Doctrine\ORM\EntityRepository
{
}
