<?php

namespace GestionFaenaBundle\Repository\gestionBD;

/**
 * RubroEntidadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RubroEntidadRepository extends \Doctrine\ORM\EntityRepository
{
}
