<?php

namespace GestionFaenaBundle\Repository\gestionBD;

/**
 * SubcategoriaArticuloRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubcategoriaArticuloRepository extends \Doctrine\ORM\EntityRepository
{
}
