<?php

namespace GestionFaenaBundle\Repository\gestionBD;

/**
 * TransportistaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransportistaRepository extends \Doctrine\ORM\EntityRepository
{
	public function getActivos() 
	{ 
			return $this->createQueryBuilder('t')
						->where('t.activo = :activo')
						->setParameter('activo', true)
						->orderBy('t.titular')
						->getQuery()
						->getResult();
	} 
}
