<?php

namespace GestionFaenaBundle\Repository\opciones;

/**
 * PosicionAtributoInformeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PosicionAtributoInformeRepository extends \Doctrine\ORM\EntityRepository
{
}
