<?php

namespace GestionFaenaBundle\Repository\opciones;

/**
 * CalculoFaenaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CalculoFaenaRepository extends \Doctrine\ORM\EntityRepository
{
	public function findCalculo($calculo) 
	{ 
	    return $this->createQueryBuilder('c')
			        ->where('c.calculo = :calculo')
			        ->setParameter('calculo', $calculo)
			        ->getQuery()
			        ->getOneOrNullResult(); 
	} 
}
