<?php

namespace GestionFaenaBundle\Repository\opciones;

/**
 * InformeProcesoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InformeProcesoRepository extends \Doctrine\ORM\EntityRepository
{
}
