<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHyzexmd\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHyzexmd/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerHyzexmd.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerHyzexmd\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerHyzexmd\appDevDebugProjectContainer([
    'container.build_hash' => 'Hyzexmd',
    'container.build_id' => '57d37a25',
    'container.build_time' => 1621023348,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHyzexmd');
