<?php

namespace Proxies\__CG__\GestionFaenaBundle\Entity\gestionBD;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Articulo extends \GestionFaenaBundle\Entity\gestionBD\Articulo implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'GestionFaenaBundle\\Entity\\gestionBD\\Articulo' . "\0" . 'id', '' . "\0" . 'GestionFaenaBundle\\Entity\\gestionBD\\Articulo' . "\0" . 'codigoInterno', '' . "\0" . 'GestionFaenaBundle\\Entity\\gestionBD\\Articulo' . "\0" . 'nombre', '' . "\0" . 'GestionFaenaBundle\\Entity\\gestionBD\\Articulo' . "\0" . 'nombreResumido', '' . "\0" . 'GestionFaenaBundle\\Entity\\gestionBD\\Articulo' . "\0" . 'codigoSenasa', '' . "\0" . 'GestionFaenaBundle\\Entity\\gestionBD\\Articulo' . "\0" . 'nombreSenasa', '' . "\0" . 'GestionFaenaBundle\\Entity\\gestionBD\\Articulo' . "\0" . 'artsAtrConc', '' . "\0" . 'GestionFaenaBundle\\Entity\\gestionBD\\Articulo' . "\0" . 'presentacionKg', '' . "\0" . 'GestionFaenaBundle\\Entity\\gestionBD\\Articulo' . "\0" . 'presentacionUnidad', '' . "\0" . 'GestionFaenaBundle\\Entity\\gestionBD\\Articulo' . "\0" . 'categoria', '' . "\0" . 'GestionFaenaBundle\\Entity\\gestionBD\\Articulo' . "\0" . 'subcategoria', '' . "\0" . 'GestionFaenaBundle\\Entity\\gestionBD\\Articulo' . "\0" . 'eliminado', '' . "\0" . 'GestionFaenaBundle\\Entity\\gestionBD\\Articulo' . "\0" . 'orden', '' . "\0" . 'GestionFaenaBundle\\Entity\\gestionBD\\Articulo' . "\0" . 'clasificable', '' . "\0" . 'GestionFaenaBundle\\Entity\\gestionBD\\Articulo' . "\0" . 'articulosClasificables', '' . "\0" . 'GestionFaenaBundle\\Entity\\gestionBD\\Articulo' . "\0" . 'articuloBase', '' . "\0" . 'GestionFaenaBundle\\Entity\\gestionBD\\Articulo' . "\0" . 'descVenta'];
        }

        return ['__isInitialized__', '' . "\0" . 'GestionFaenaBundle\\Entity\\gestionBD\\Articulo' . "\0" . 'id', '' . "\0" . 'GestionFaenaBundle\\Entity\\gestionBD\\Articulo' . "\0" . 'codigoInterno', '' . "\0" . 'GestionFaenaBundle\\Entity\\gestionBD\\Articulo' . "\0" . 'nombre', '' . "\0" . 'GestionFaenaBundle\\Entity\\gestionBD\\Articulo' . "\0" . 'nombreResumido', '' . "\0" . 'GestionFaenaBundle\\Entity\\gestionBD\\Articulo' . "\0" . 'codigoSenasa', '' . "\0" . 'GestionFaenaBundle\\Entity\\gestionBD\\Articulo' . "\0" . 'nombreSenasa', '' . "\0" . 'GestionFaenaBundle\\Entity\\gestionBD\\Articulo' . "\0" . 'artsAtrConc', '' . "\0" . 'GestionFaenaBundle\\Entity\\gestionBD\\Articulo' . "\0" . 'presentacionKg', '' . "\0" . 'GestionFaenaBundle\\Entity\\gestionBD\\Articulo' . "\0" . 'presentacionUnidad', '' . "\0" . 'GestionFaenaBundle\\Entity\\gestionBD\\Articulo' . "\0" . 'categoria', '' . "\0" . 'GestionFaenaBundle\\Entity\\gestionBD\\Articulo' . "\0" . 'subcategoria', '' . "\0" . 'GestionFaenaBundle\\Entity\\gestionBD\\Articulo' . "\0" . 'eliminado', '' . "\0" . 'GestionFaenaBundle\\Entity\\gestionBD\\Articulo' . "\0" . 'orden', '' . "\0" . 'GestionFaenaBundle\\Entity\\gestionBD\\Articulo' . "\0" . 'clasificable', '' . "\0" . 'GestionFaenaBundle\\Entity\\gestionBD\\Articulo' . "\0" . 'articulosClasificables', '' . "\0" . 'GestionFaenaBundle\\Entity\\gestionBD\\Articulo' . "\0" . 'articuloBase', '' . "\0" . 'GestionFaenaBundle\\Entity\\gestionBD\\Articulo' . "\0" . 'descVenta'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Articulo $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getNombreVenta()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombreVenta', []);

        return parent::getNombreVenta();
    }

    /**
     * {@inheritDoc}
     */
    public function serialize()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'serialize', []);

        return parent::serialize();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombre($nombre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombre', [$nombre]);

        return parent::setNombre($nombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombre', []);

        return parent::getNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function addArtsAtrConc(\GestionFaenaBundle\Entity\gestionBD\ArticuloAtributoConcepto $artsAtrConc)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addArtsAtrConc', [$artsAtrConc]);

        return parent::addArtsAtrConc($artsAtrConc);
    }

    /**
     * {@inheritDoc}
     */
    public function removeArtsAtrConc(\GestionFaenaBundle\Entity\gestionBD\ArticuloAtributoConcepto $artsAtrConc)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeArtsAtrConc', [$artsAtrConc]);

        return parent::removeArtsAtrConc($artsAtrConc);
    }

    /**
     * {@inheritDoc}
     */
    public function getArtsAtrConc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArtsAtrConc', []);

        return parent::getArtsAtrConc();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodigoSenasa($codigoSenasa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodigoSenasa', [$codigoSenasa]);

        return parent::setCodigoSenasa($codigoSenasa);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodigoSenasa()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodigoSenasa', []);

        return parent::getCodigoSenasa();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombreSenasa($nombreSenasa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombreSenasa', [$nombreSenasa]);

        return parent::setNombreSenasa($nombreSenasa);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombreSenasa()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombreSenasa', []);

        return parent::getNombreSenasa();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodigoInterno($codigoInterno)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodigoInterno', [$codigoInterno]);

        return parent::setCodigoInterno($codigoInterno);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodigoInterno()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodigoInterno', []);

        return parent::getCodigoInterno();
    }

    /**
     * {@inheritDoc}
     */
    public function setPresentacionKg($presentacionKg)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPresentacionKg', [$presentacionKg]);

        return parent::setPresentacionKg($presentacionKg);
    }

    /**
     * {@inheritDoc}
     */
    public function getPresentacionKg()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPresentacionKg', []);

        return parent::getPresentacionKg();
    }

    /**
     * {@inheritDoc}
     */
    public function setPresentacionUnidad($presentacionUnidad)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPresentacionUnidad', [$presentacionUnidad]);

        return parent::setPresentacionUnidad($presentacionUnidad);
    }

    /**
     * {@inheritDoc}
     */
    public function getPresentacionUnidad()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPresentacionUnidad', []);

        return parent::getPresentacionUnidad();
    }

    /**
     * {@inheritDoc}
     */
    public function setCategoria(\GestionFaenaBundle\Entity\gestionBD\CategoriaArticulo $categoria = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategoria', [$categoria]);

        return parent::setCategoria($categoria);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategoria()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategoria', []);

        return parent::getCategoria();
    }

    /**
     * {@inheritDoc}
     */
    public function setSubcategoria(\GestionFaenaBundle\Entity\gestionBD\SubcategoriaArticulo $subcategoria = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSubcategoria', [$subcategoria]);

        return parent::setSubcategoria($subcategoria);
    }

    /**
     * {@inheritDoc}
     */
    public function getSubcategoria()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSubcategoria', []);

        return parent::getSubcategoria();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombreResumido($nombreResumido)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombreResumido', [$nombreResumido]);

        return parent::setNombreResumido($nombreResumido);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombreResumido()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombreResumido', []);

        return parent::getNombreResumido();
    }

    /**
     * {@inheritDoc}
     */
    public function setEliminado($eliminado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEliminado', [$eliminado]);

        return parent::setEliminado($eliminado);
    }

    /**
     * {@inheritDoc}
     */
    public function getEliminado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEliminado', []);

        return parent::getEliminado();
    }

    /**
     * {@inheritDoc}
     */
    public function setOrden($orden)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrden', [$orden]);

        return parent::setOrden($orden);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrden()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrden', []);

        return parent::getOrden();
    }

    /**
     * {@inheritDoc}
     */
    public function setClasificable($clasificable)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClasificable', [$clasificable]);

        return parent::setClasificable($clasificable);
    }

    /**
     * {@inheritDoc}
     */
    public function getClasificable()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClasificable', []);

        return parent::getClasificable();
    }

    /**
     * {@inheritDoc}
     */
    public function addArticulosClasificable(\GestionFaenaBundle\Entity\gestionBD\Articulo $articulosClasificable)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addArticulosClasificable', [$articulosClasificable]);

        return parent::addArticulosClasificable($articulosClasificable);
    }

    /**
     * {@inheritDoc}
     */
    public function removeArticulosClasificable(\GestionFaenaBundle\Entity\gestionBD\Articulo $articulosClasificable)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeArticulosClasificable', [$articulosClasificable]);

        return parent::removeArticulosClasificable($articulosClasificable);
    }

    /**
     * {@inheritDoc}
     */
    public function getArticulosClasificables()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArticulosClasificables', []);

        return parent::getArticulosClasificables();
    }

    /**
     * {@inheritDoc}
     */
    public function setArticuloBase(\GestionFaenaBundle\Entity\gestionBD\Articulo $articuloBase = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArticuloBase', [$articuloBase]);

        return parent::setArticuloBase($articuloBase);
    }

    /**
     * {@inheritDoc}
     */
    public function getArticuloBase()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArticuloBase', []);

        return parent::getArticuloBase();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescVenta($descVenta)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescVenta', [$descVenta]);

        return parent::setDescVenta($descVenta);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescVenta()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescVenta', []);

        return parent::getDescVenta();
    }

}
