<?php

namespace Proxies\__CG__\GestionFaenaBundle\Entity\opciones;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class InformeProceso extends \GestionFaenaBundle\Entity\opciones\InformeProceso implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'GestionFaenaBundle\\Entity\\opciones\\InformeProceso' . "\0" . 'id', '' . "\0" . 'GestionFaenaBundle\\Entity\\opciones\\InformeProceso' . "\0" . 'conceptos', '' . "\0" . 'GestionFaenaBundle\\Entity\\opciones\\InformeProceso' . "\0" . 'atributos', '' . "\0" . 'GestionFaenaBundle\\Entity\\opciones\\InformeProceso' . "\0" . 'proceso', '' . "\0" . 'GestionFaenaBundle\\Entity\\opciones\\InformeProceso' . "\0" . 'atributoAjuste'];
        }

        return ['__isInitialized__', '' . "\0" . 'GestionFaenaBundle\\Entity\\opciones\\InformeProceso' . "\0" . 'id', '' . "\0" . 'GestionFaenaBundle\\Entity\\opciones\\InformeProceso' . "\0" . 'conceptos', '' . "\0" . 'GestionFaenaBundle\\Entity\\opciones\\InformeProceso' . "\0" . 'atributos', '' . "\0" . 'GestionFaenaBundle\\Entity\\opciones\\InformeProceso' . "\0" . 'proceso', '' . "\0" . 'GestionFaenaBundle\\Entity\\opciones\\InformeProceso' . "\0" . 'atributoAjuste'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (InformeProceso $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function addConcepto(\GestionFaenaBundle\Entity\faena\ConceptoMovimiento $concepto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addConcepto', [$concepto]);

        return parent::addConcepto($concepto);
    }

    /**
     * {@inheritDoc}
     */
    public function removeConcepto(\GestionFaenaBundle\Entity\faena\ConceptoMovimiento $concepto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeConcepto', [$concepto]);

        return parent::removeConcepto($concepto);
    }

    /**
     * {@inheritDoc}
     */
    public function getConceptos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConceptos', []);

        return parent::getConceptos();
    }

    /**
     * {@inheritDoc}
     */
    public function setProceso(\GestionFaenaBundle\Entity\ProcesoFaena $proceso = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProceso', [$proceso]);

        return parent::setProceso($proceso);
    }

    /**
     * {@inheritDoc}
     */
    public function getProceso()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProceso', []);

        return parent::getProceso();
    }

    /**
     * {@inheritDoc}
     */
    public function addAtributo(\GestionFaenaBundle\Entity\opciones\AtributoInforme $atributo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAtributo', [$atributo]);

        return parent::addAtributo($atributo);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAtributo(\GestionFaenaBundle\Entity\opciones\AtributoInforme $atributo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAtributo', [$atributo]);

        return parent::removeAtributo($atributo);
    }

    /**
     * {@inheritDoc}
     */
    public function getAtributos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAtributos', []);

        return parent::getAtributos();
    }

    /**
     * {@inheritDoc}
     */
    public function getAtrWhitSort($orden)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAtrWhitSort', [$orden]);

        return parent::getAtrWhitSort($orden);
    }

    /**
     * {@inheritDoc}
     */
    public function getAtributoAgrupa()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAtributoAgrupa', []);

        return parent::getAtributoAgrupa();
    }

    /**
     * {@inheritDoc}
     */
    public function getAtributosAcumulables()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAtributosAcumulables', []);

        return parent::getAtributosAcumulables();
    }

    /**
     * {@inheritDoc}
     */
    public function setAtributoAjuste(\GestionFaenaBundle\Entity\gestionBD\Atributo $atributoAjuste = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAtributoAjuste', [$atributoAjuste]);

        return parent::setAtributoAjuste($atributoAjuste);
    }

    /**
     * {@inheritDoc}
     */
    public function getAtributoAjuste()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAtributoAjuste', []);

        return parent::getAtributoAjuste();
    }

}
