<?php

namespace Proxies\__CG__\GestionSigcerBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class DetalleSolicitud extends \GestionSigcerBundle\Entity\DetalleSolicitud implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'GestionSigcerBundle\\Entity\\DetalleSolicitud' . "\0" . 'id', '' . "\0" . 'GestionSigcerBundle\\Entity\\DetalleSolicitud' . "\0" . 'pesoNeto', '' . "\0" . 'GestionSigcerBundle\\Entity\\DetalleSolicitud' . "\0" . 'pesoBruto', '' . "\0" . 'GestionSigcerBundle\\Entity\\DetalleSolicitud' . "\0" . 'cantidad', '' . "\0" . 'GestionSigcerBundle\\Entity\\DetalleSolicitud' . "\0" . 'cantidadSanitario', '' . "\0" . 'GestionSigcerBundle\\Entity\\DetalleSolicitud' . "\0" . 'certificadoOrigen', '' . "\0" . 'GestionSigcerBundle\\Entity\\DetalleSolicitud' . "\0" . 'articulo', '' . "\0" . 'GestionSigcerBundle\\Entity\\DetalleSolicitud' . "\0" . 'tropa', '' . "\0" . 'GestionSigcerBundle\\Entity\\DetalleSolicitud' . "\0" . 'envasePrimario', '' . "\0" . 'GestionSigcerBundle\\Entity\\DetalleSolicitud' . "\0" . 'envaseSecundario', '' . "\0" . 'GestionSigcerBundle\\Entity\\DetalleSolicitud' . "\0" . 'solicitud'];
        }

        return ['__isInitialized__', '' . "\0" . 'GestionSigcerBundle\\Entity\\DetalleSolicitud' . "\0" . 'id', '' . "\0" . 'GestionSigcerBundle\\Entity\\DetalleSolicitud' . "\0" . 'pesoNeto', '' . "\0" . 'GestionSigcerBundle\\Entity\\DetalleSolicitud' . "\0" . 'pesoBruto', '' . "\0" . 'GestionSigcerBundle\\Entity\\DetalleSolicitud' . "\0" . 'cantidad', '' . "\0" . 'GestionSigcerBundle\\Entity\\DetalleSolicitud' . "\0" . 'cantidadSanitario', '' . "\0" . 'GestionSigcerBundle\\Entity\\DetalleSolicitud' . "\0" . 'certificadoOrigen', '' . "\0" . 'GestionSigcerBundle\\Entity\\DetalleSolicitud' . "\0" . 'articulo', '' . "\0" . 'GestionSigcerBundle\\Entity\\DetalleSolicitud' . "\0" . 'tropa', '' . "\0" . 'GestionSigcerBundle\\Entity\\DetalleSolicitud' . "\0" . 'envasePrimario', '' . "\0" . 'GestionSigcerBundle\\Entity\\DetalleSolicitud' . "\0" . 'envaseSecundario', '' . "\0" . 'GestionSigcerBundle\\Entity\\DetalleSolicitud' . "\0" . 'solicitud'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (DetalleSolicitud $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setPesoNeto($pesoNeto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPesoNeto', [$pesoNeto]);

        return parent::setPesoNeto($pesoNeto);
    }

    /**
     * {@inheritDoc}
     */
    public function getPesoNeto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPesoNeto', []);

        return parent::getPesoNeto();
    }

    /**
     * {@inheritDoc}
     */
    public function setPesoBruto($pesoBruto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPesoBruto', [$pesoBruto]);

        return parent::setPesoBruto($pesoBruto);
    }

    /**
     * {@inheritDoc}
     */
    public function getPesoBruto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPesoBruto', []);

        return parent::getPesoBruto();
    }

    /**
     * {@inheritDoc}
     */
    public function setCantidad($cantidad)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCantidad', [$cantidad]);

        return parent::setCantidad($cantidad);
    }

    /**
     * {@inheritDoc}
     */
    public function getCantidad()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCantidad', []);

        return parent::getCantidad();
    }

    /**
     * {@inheritDoc}
     */
    public function setCertificadoOrigen($certificadoOrigen)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCertificadoOrigen', [$certificadoOrigen]);

        return parent::setCertificadoOrigen($certificadoOrigen);
    }

    /**
     * {@inheritDoc}
     */
    public function getCertificadoOrigen()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCertificadoOrigen', []);

        return parent::getCertificadoOrigen();
    }

    /**
     * {@inheritDoc}
     */
    public function setTropa(\GestionSigcerBundle\Entity\TropaSolicitud $tropa = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTropa', [$tropa]);

        return parent::setTropa($tropa);
    }

    /**
     * {@inheritDoc}
     */
    public function getTropa()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTropa', []);

        return parent::getTropa();
    }

    /**
     * {@inheritDoc}
     */
    public function setEnvasePrimario(\GestionSigcerBundle\Entity\opciones\Envase $envasePrimario = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEnvasePrimario', [$envasePrimario]);

        return parent::setEnvasePrimario($envasePrimario);
    }

    /**
     * {@inheritDoc}
     */
    public function getEnvasePrimario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEnvasePrimario', []);

        return parent::getEnvasePrimario();
    }

    /**
     * {@inheritDoc}
     */
    public function setEnvaseSecundario(\GestionSigcerBundle\Entity\opciones\Envase $envaseSecundario = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEnvaseSecundario', [$envaseSecundario]);

        return parent::setEnvaseSecundario($envaseSecundario);
    }

    /**
     * {@inheritDoc}
     */
    public function getEnvaseSecundario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEnvaseSecundario', []);

        return parent::getEnvaseSecundario();
    }

    /**
     * {@inheritDoc}
     */
    public function setSolicitud(\GestionSigcerBundle\Entity\Solicitud $solicitud = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSolicitud', [$solicitud]);

        return parent::setSolicitud($solicitud);
    }

    /**
     * {@inheritDoc}
     */
    public function getSolicitud()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSolicitud', []);

        return parent::getSolicitud();
    }

    /**
     * {@inheritDoc}
     */
    public function setArticulo(\GestionSigcerBundle\Entity\opciones\Producto $articulo = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArticulo', [$articulo]);

        return parent::setArticulo($articulo);
    }

    /**
     * {@inheritDoc}
     */
    public function getArticulo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArticulo', []);

        return parent::getArticulo();
    }

    /**
     * {@inheritDoc}
     */
    public function setCantidadSanitario($cantidadSanitario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCantidadSanitario', [$cantidadSanitario]);

        return parent::setCantidadSanitario($cantidadSanitario);
    }

    /**
     * {@inheritDoc}
     */
    public function getCantidadSanitario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCantidadSanitario', []);

        return parent::getCantidadSanitario();
    }

}
