<?php

namespace Proxies\__CG__\GestionSigcerBundle\Entity\opciones;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Camion extends \GestionSigcerBundle\Entity\opciones\Camion implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'GestionSigcerBundle\\Entity\\opciones\\Camion' . "\0" . 'id', '' . "\0" . 'GestionSigcerBundle\\Entity\\opciones\\Camion' . "\0" . 'tipo', '' . "\0" . 'GestionSigcerBundle\\Entity\\opciones\\Camion' . "\0" . 'patente', '' . "\0" . 'GestionSigcerBundle\\Entity\\opciones\\Camion' . "\0" . 'senasa', '' . "\0" . 'GestionSigcerBundle\\Entity\\opciones\\Camion' . "\0" . 'cantPrecintos'];
        }

        return ['__isInitialized__', '' . "\0" . 'GestionSigcerBundle\\Entity\\opciones\\Camion' . "\0" . 'id', '' . "\0" . 'GestionSigcerBundle\\Entity\\opciones\\Camion' . "\0" . 'tipo', '' . "\0" . 'GestionSigcerBundle\\Entity\\opciones\\Camion' . "\0" . 'patente', '' . "\0" . 'GestionSigcerBundle\\Entity\\opciones\\Camion' . "\0" . 'senasa', '' . "\0" . 'GestionSigcerBundle\\Entity\\opciones\\Camion' . "\0" . 'cantPrecintos'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Camion $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setPatente($patente)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPatente', [$patente]);

        return parent::setPatente($patente);
    }

    /**
     * {@inheritDoc}
     */
    public function getPatente()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPatente', []);

        return parent::getPatente();
    }

    /**
     * {@inheritDoc}
     */
    public function setSenasa($senasa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSenasa', [$senasa]);

        return parent::setSenasa($senasa);
    }

    /**
     * {@inheritDoc}
     */
    public function getSenasa()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSenasa', []);

        return parent::getSenasa();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipo($tipo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipo', [$tipo]);

        return parent::setTipo($tipo);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipo', []);

        return parent::getTipo();
    }

    /**
     * {@inheritDoc}
     */
    public function setCantPrecintos($cantPrecintos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCantPrecintos', [$cantPrecintos]);

        return parent::setCantPrecintos($cantPrecintos);
    }

    /**
     * {@inheritDoc}
     */
    public function getCantPrecintos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCantPrecintos', []);

        return parent::getCantPrecintos();
    }

}
