<?php

namespace Proxies\__CG__\GestionSigcerBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Solicitud extends \GestionSigcerBundle\Entity\Solicitud implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'GestionSigcerBundle\\Entity\\Solicitud' . "\0" . 'id', '' . "\0" . 'GestionSigcerBundle\\Entity\\Solicitud' . "\0" . 'zona', '' . "\0" . 'GestionSigcerBundle\\Entity\\Solicitud' . "\0" . 'lugarDestino', '' . "\0" . 'GestionSigcerBundle\\Entity\\Solicitud' . "\0" . 'precintos', '' . "\0" . 'GestionSigcerBundle\\Entity\\Solicitud' . "\0" . 'precintoAduana', '' . "\0" . 'GestionSigcerBundle\\Entity\\Solicitud' . "\0" . 'precintoSenasa', '' . "\0" . 'GestionSigcerBundle\\Entity\\Solicitud' . "\0" . 'observaciones', '' . "\0" . 'GestionSigcerBundle\\Entity\\Solicitud' . "\0" . 'remitoNumero', '' . "\0" . 'GestionSigcerBundle\\Entity\\Solicitud' . "\0" . 'temperatura', '' . "\0" . 'GestionSigcerBundle\\Entity\\Solicitud' . "\0" . 'termoTemperatura', '' . "\0" . 'GestionSigcerBundle\\Entity\\Solicitud' . "\0" . 'termoTiempo', '' . "\0" . 'GestionSigcerBundle\\Entity\\Solicitud' . "\0" . 'cliente', '' . "\0" . 'GestionSigcerBundle\\Entity\\Solicitud' . "\0" . 'camion', '' . "\0" . 'GestionSigcerBundle\\Entity\\Solicitud' . "\0" . 'detalles', '' . "\0" . 'GestionSigcerBundle\\Entity\\Solicitud' . "\0" . 'grupo', '' . "\0" . 'GestionSigcerBundle\\Entity\\Solicitud' . "\0" . 'patenteCamion', '' . "\0" . 'GestionSigcerBundle\\Entity\\Solicitud' . "\0" . 'patenteAcoplado', '' . "\0" . 'GestionSigcerBundle\\Entity\\Solicitud' . "\0" . 'destinatarioExportacion', '' . "\0" . 'GestionSigcerBundle\\Entity\\Solicitud' . "\0" . 'tipoTransporte', '' . "\0" . 'GestionSigcerBundle\\Entity\\Solicitud' . "\0" . 'numeroContenedor', '' . "\0" . 'GestionSigcerBundle\\Entity\\Solicitud' . "\0" . 'nombreBuque'];
        }

        return ['__isInitialized__', '' . "\0" . 'GestionSigcerBundle\\Entity\\Solicitud' . "\0" . 'id', '' . "\0" . 'GestionSigcerBundle\\Entity\\Solicitud' . "\0" . 'zona', '' . "\0" . 'GestionSigcerBundle\\Entity\\Solicitud' . "\0" . 'lugarDestino', '' . "\0" . 'GestionSigcerBundle\\Entity\\Solicitud' . "\0" . 'precintos', '' . "\0" . 'GestionSigcerBundle\\Entity\\Solicitud' . "\0" . 'precintoAduana', '' . "\0" . 'GestionSigcerBundle\\Entity\\Solicitud' . "\0" . 'precintoSenasa', '' . "\0" . 'GestionSigcerBundle\\Entity\\Solicitud' . "\0" . 'observaciones', '' . "\0" . 'GestionSigcerBundle\\Entity\\Solicitud' . "\0" . 'remitoNumero', '' . "\0" . 'GestionSigcerBundle\\Entity\\Solicitud' . "\0" . 'temperatura', '' . "\0" . 'GestionSigcerBundle\\Entity\\Solicitud' . "\0" . 'termoTemperatura', '' . "\0" . 'GestionSigcerBundle\\Entity\\Solicitud' . "\0" . 'termoTiempo', '' . "\0" . 'GestionSigcerBundle\\Entity\\Solicitud' . "\0" . 'cliente', '' . "\0" . 'GestionSigcerBundle\\Entity\\Solicitud' . "\0" . 'camion', '' . "\0" . 'GestionSigcerBundle\\Entity\\Solicitud' . "\0" . 'detalles', '' . "\0" . 'GestionSigcerBundle\\Entity\\Solicitud' . "\0" . 'grupo', '' . "\0" . 'GestionSigcerBundle\\Entity\\Solicitud' . "\0" . 'patenteCamion', '' . "\0" . 'GestionSigcerBundle\\Entity\\Solicitud' . "\0" . 'patenteAcoplado', '' . "\0" . 'GestionSigcerBundle\\Entity\\Solicitud' . "\0" . 'destinatarioExportacion', '' . "\0" . 'GestionSigcerBundle\\Entity\\Solicitud' . "\0" . 'tipoTransporte', '' . "\0" . 'GestionSigcerBundle\\Entity\\Solicitud' . "\0" . 'numeroContenedor', '' . "\0" . 'GestionSigcerBundle\\Entity\\Solicitud' . "\0" . 'nombreBuque'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Solicitud $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setLugarDestino($lugarDestino)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLugarDestino', [$lugarDestino]);

        return parent::setLugarDestino($lugarDestino);
    }

    /**
     * {@inheritDoc}
     */
    public function getLugarDestino()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLugarDestino', []);

        return parent::getLugarDestino();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrecintoAduana($precintoAduana)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrecintoAduana', [$precintoAduana]);

        return parent::setPrecintoAduana($precintoAduana);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrecintoAduana()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrecintoAduana', []);

        return parent::getPrecintoAduana();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrecintoSenasa($precintoSenasa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrecintoSenasa', [$precintoSenasa]);

        return parent::setPrecintoSenasa($precintoSenasa);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrecintoSenasa()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrecintoSenasa', []);

        return parent::getPrecintoSenasa();
    }

    /**
     * {@inheritDoc}
     */
    public function setObservaciones($observaciones)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setObservaciones', [$observaciones]);

        return parent::setObservaciones($observaciones);
    }

    /**
     * {@inheritDoc}
     */
    public function getObservaciones()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObservaciones', []);

        return parent::getObservaciones();
    }

    /**
     * {@inheritDoc}
     */
    public function setRemitoNumero($remitoNumero)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRemitoNumero', [$remitoNumero]);

        return parent::setRemitoNumero($remitoNumero);
    }

    /**
     * {@inheritDoc}
     */
    public function getRemitoNumero()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRemitoNumero', []);

        return parent::getRemitoNumero();
    }

    /**
     * {@inheritDoc}
     */
    public function setTemperatura($temperatura)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTemperatura', [$temperatura]);

        return parent::setTemperatura($temperatura);
    }

    /**
     * {@inheritDoc}
     */
    public function getTemperatura()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTemperatura', []);

        return parent::getTemperatura();
    }

    /**
     * {@inheritDoc}
     */
    public function setTermoTemperatura($termoTemperatura)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTermoTemperatura', [$termoTemperatura]);

        return parent::setTermoTemperatura($termoTemperatura);
    }

    /**
     * {@inheritDoc}
     */
    public function getTermoTemperatura()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTermoTemperatura', []);

        return parent::getTermoTemperatura();
    }

    /**
     * {@inheritDoc}
     */
    public function setTermoTiempo($termoTiempo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTermoTiempo', [$termoTiempo]);

        return parent::setTermoTiempo($termoTiempo);
    }

    /**
     * {@inheritDoc}
     */
    public function getTermoTiempo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTermoTiempo', []);

        return parent::getTermoTiempo();
    }

    /**
     * {@inheritDoc}
     */
    public function setCliente(\GestionSigcerBundle\Entity\opciones\Cliente $cliente = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCliente', [$cliente]);

        return parent::setCliente($cliente);
    }

    /**
     * {@inheritDoc}
     */
    public function getCliente()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCliente', []);

        return parent::getCliente();
    }

    /**
     * {@inheritDoc}
     */
    public function setCamion(\GestionSigcerBundle\Entity\opciones\Camion $camion = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCamion', [$camion]);

        return parent::setCamion($camion);
    }

    /**
     * {@inheritDoc}
     */
    public function getCamion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCamion', []);

        return parent::getCamion();
    }

    /**
     * {@inheritDoc}
     */
    public function addDetalle(\GestionSigcerBundle\Entity\DetalleSolicitud $detalle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addDetalle', [$detalle]);

        return parent::addDetalle($detalle);
    }

    /**
     * {@inheritDoc}
     */
    public function removeDetalle(\GestionSigcerBundle\Entity\DetalleSolicitud $detalle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeDetalle', [$detalle]);

        return parent::removeDetalle($detalle);
    }

    /**
     * {@inheritDoc}
     */
    public function getDetalles()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDetalles', []);

        return parent::getDetalles();
    }

    /**
     * {@inheritDoc}
     */
    public function setGrupo(\GestionSigcerBundle\Entity\GrupoSolicitud $grupo = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGrupo', [$grupo]);

        return parent::setGrupo($grupo);
    }

    /**
     * {@inheritDoc}
     */
    public function getGrupo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGrupo', []);

        return parent::getGrupo();
    }

    /**
     * {@inheritDoc}
     */
    public function setZona(\GestionSigcerBundle\Entity\opciones\Zona $zona = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setZona', [$zona]);

        return parent::setZona($zona);
    }

    /**
     * {@inheritDoc}
     */
    public function getZona()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getZona', []);

        return parent::getZona();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrecintos($precintos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrecintos', [$precintos]);

        return parent::setPrecintos($precintos);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrecintos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrecintos', []);

        return parent::getPrecintos();
    }

    /**
     * {@inheritDoc}
     */
    public function setPatenteCamion($patenteCamion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPatenteCamion', [$patenteCamion]);

        return parent::setPatenteCamion($patenteCamion);
    }

    /**
     * {@inheritDoc}
     */
    public function getPatenteCamion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPatenteCamion', []);

        return parent::getPatenteCamion();
    }

    /**
     * {@inheritDoc}
     */
    public function setPatenteAcoplado($patenteAcoplado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPatenteAcoplado', [$patenteAcoplado]);

        return parent::setPatenteAcoplado($patenteAcoplado);
    }

    /**
     * {@inheritDoc}
     */
    public function getPatenteAcoplado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPatenteAcoplado', []);

        return parent::getPatenteAcoplado();
    }

    /**
     * {@inheritDoc}
     */
    public function setDestinatarioExportacion(\GestionSigcerBundle\Entity\opciones\DestinatarioExportacion $destinatarioExportacion = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDestinatarioExportacion', [$destinatarioExportacion]);

        return parent::setDestinatarioExportacion($destinatarioExportacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getDestinatarioExportacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDestinatarioExportacion', []);

        return parent::getDestinatarioExportacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipoTransporte($tipoTransporte)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipoTransporte', [$tipoTransporte]);

        return parent::setTipoTransporte($tipoTransporte);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipoTransporte()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipoTransporte', []);

        return parent::getTipoTransporte();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumeroContenedor($numeroContenedor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumeroContenedor', [$numeroContenedor]);

        return parent::setNumeroContenedor($numeroContenedor);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumeroContenedor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumeroContenedor', []);

        return parent::getNumeroContenedor();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombreBuque($nombreBuque)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombreBuque', [$nombreBuque]);

        return parent::setNombreBuque($nombreBuque);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombreBuque()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombreBuque', []);

        return parent::getNombreBuque();
    }

}
