<?php

namespace Proxies\__CG__\GestionSigcerBundle\Entity\opciones;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Producto extends \GestionSigcerBundle\Entity\opciones\Producto implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'GestionSigcerBundle\\Entity\\opciones\\Producto' . "\0" . 'id', '' . "\0" . 'GestionSigcerBundle\\Entity\\opciones\\Producto' . "\0" . 'nombre', '' . "\0" . 'GestionSigcerBundle\\Entity\\opciones\\Producto' . "\0" . 'codigoCapa', '' . "\0" . 'GestionSigcerBundle\\Entity\\opciones\\Producto' . "\0" . 'marca', '' . "\0" . 'GestionSigcerBundle\\Entity\\opciones\\Producto' . "\0" . 'envasePrimario', '' . "\0" . 'GestionSigcerBundle\\Entity\\opciones\\Producto' . "\0" . 'envaseSecundario', '' . "\0" . 'GestionSigcerBundle\\Entity\\opciones\\Producto' . "\0" . 'ajusteBruto', '' . "\0" . 'GestionSigcerBundle\\Entity\\opciones\\Producto' . "\0" . 'ajusteNeto', '' . "\0" . 'GestionSigcerBundle\\Entity\\opciones\\Producto' . "\0" . 'ajusteCantidad', '' . "\0" . 'GestionSigcerBundle\\Entity\\opciones\\Producto' . "\0" . 'destino'];
        }

        return ['__isInitialized__', '' . "\0" . 'GestionSigcerBundle\\Entity\\opciones\\Producto' . "\0" . 'id', '' . "\0" . 'GestionSigcerBundle\\Entity\\opciones\\Producto' . "\0" . 'nombre', '' . "\0" . 'GestionSigcerBundle\\Entity\\opciones\\Producto' . "\0" . 'codigoCapa', '' . "\0" . 'GestionSigcerBundle\\Entity\\opciones\\Producto' . "\0" . 'marca', '' . "\0" . 'GestionSigcerBundle\\Entity\\opciones\\Producto' . "\0" . 'envasePrimario', '' . "\0" . 'GestionSigcerBundle\\Entity\\opciones\\Producto' . "\0" . 'envaseSecundario', '' . "\0" . 'GestionSigcerBundle\\Entity\\opciones\\Producto' . "\0" . 'ajusteBruto', '' . "\0" . 'GestionSigcerBundle\\Entity\\opciones\\Producto' . "\0" . 'ajusteNeto', '' . "\0" . 'GestionSigcerBundle\\Entity\\opciones\\Producto' . "\0" . 'ajusteCantidad', '' . "\0" . 'GestionSigcerBundle\\Entity\\opciones\\Producto' . "\0" . 'destino'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Producto $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getDestinoTxt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDestinoTxt', []);

        return parent::getDestinoTxt();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombre($nombre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombre', [$nombre]);

        return parent::setNombre($nombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombre', []);

        return parent::getNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodigoCapa($codigoCapa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodigoCapa', [$codigoCapa]);

        return parent::setCodigoCapa($codigoCapa);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodigoCapa()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodigoCapa', []);

        return parent::getCodigoCapa();
    }

    /**
     * {@inheritDoc}
     */
    public function setMarca($marca)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMarca', [$marca]);

        return parent::setMarca($marca);
    }

    /**
     * {@inheritDoc}
     */
    public function getMarca()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMarca', []);

        return parent::getMarca();
    }

    /**
     * {@inheritDoc}
     */
    public function setEnvasePrimario(\GestionSigcerBundle\Entity\opciones\Envase $envasePrimario = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEnvasePrimario', [$envasePrimario]);

        return parent::setEnvasePrimario($envasePrimario);
    }

    /**
     * {@inheritDoc}
     */
    public function getEnvasePrimario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEnvasePrimario', []);

        return parent::getEnvasePrimario();
    }

    /**
     * {@inheritDoc}
     */
    public function setEnvaseSecundario(\GestionSigcerBundle\Entity\opciones\Envase $envaseSecundario = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEnvaseSecundario', [$envaseSecundario]);

        return parent::setEnvaseSecundario($envaseSecundario);
    }

    /**
     * {@inheritDoc}
     */
    public function getEnvaseSecundario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEnvaseSecundario', []);

        return parent::getEnvaseSecundario();
    }

    /**
     * {@inheritDoc}
     */
    public function setAjusteBruto($ajusteBruto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAjusteBruto', [$ajusteBruto]);

        return parent::setAjusteBruto($ajusteBruto);
    }

    /**
     * {@inheritDoc}
     */
    public function getAjusteBruto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAjusteBruto', []);

        return parent::getAjusteBruto();
    }

    /**
     * {@inheritDoc}
     */
    public function setAjusteNeto($ajusteNeto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAjusteNeto', [$ajusteNeto]);

        return parent::setAjusteNeto($ajusteNeto);
    }

    /**
     * {@inheritDoc}
     */
    public function getAjusteNeto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAjusteNeto', []);

        return parent::getAjusteNeto();
    }

    /**
     * {@inheritDoc}
     */
    public function setAjusteCantidad($ajusteCantidad)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAjusteCantidad', [$ajusteCantidad]);

        return parent::setAjusteCantidad($ajusteCantidad);
    }

    /**
     * {@inheritDoc}
     */
    public function getAjusteCantidad()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAjusteCantidad', []);

        return parent::getAjusteCantidad();
    }

    /**
     * {@inheritDoc}
     */
    public function setDestino($destino)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDestino', [$destino]);

        return parent::setDestino($destino);
    }

    /**
     * {@inheritDoc}
     */
    public function getDestino()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDestino', []);

        return parent::getDestino();
    }

}
