<?php

namespace Proxies\__CG__\GestionFaenaBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class GrupoMovimientosAutomatico extends \GestionFaenaBundle\Entity\GrupoMovimientosAutomatico implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'GestionFaenaBundle\\Entity\\GrupoMovimientosAutomatico' . "\0" . 'id', '' . "\0" . 'GestionFaenaBundle\\Entity\\GrupoMovimientosAutomatico' . "\0" . 'orden', '' . "\0" . 'GestionFaenaBundle\\Entity\\GrupoMovimientosAutomatico' . "\0" . 'nombre', '' . "\0" . 'GestionFaenaBundle\\Entity\\GrupoMovimientosAutomatico' . "\0" . 'detalle', '' . "\0" . 'GestionFaenaBundle\\Entity\\GrupoMovimientosAutomatico' . "\0" . 'procesoFaena', '' . "\0" . 'GestionFaenaBundle\\Entity\\GrupoMovimientosAutomatico' . "\0" . 'automaticos', '' . "\0" . 'GestionFaenaBundle\\Entity\\GrupoMovimientosAutomatico' . "\0" . 'manual', '' . "\0" . 'GestionFaenaBundle\\Entity\\GrupoMovimientosAutomatico' . "\0" . 'eliminado'];
        }

        return ['__isInitialized__', '' . "\0" . 'GestionFaenaBundle\\Entity\\GrupoMovimientosAutomatico' . "\0" . 'id', '' . "\0" . 'GestionFaenaBundle\\Entity\\GrupoMovimientosAutomatico' . "\0" . 'orden', '' . "\0" . 'GestionFaenaBundle\\Entity\\GrupoMovimientosAutomatico' . "\0" . 'nombre', '' . "\0" . 'GestionFaenaBundle\\Entity\\GrupoMovimientosAutomatico' . "\0" . 'detalle', '' . "\0" . 'GestionFaenaBundle\\Entity\\GrupoMovimientosAutomatico' . "\0" . 'procesoFaena', '' . "\0" . 'GestionFaenaBundle\\Entity\\GrupoMovimientosAutomatico' . "\0" . 'automaticos', '' . "\0" . 'GestionFaenaBundle\\Entity\\GrupoMovimientosAutomatico' . "\0" . 'manual', '' . "\0" . 'GestionFaenaBundle\\Entity\\GrupoMovimientosAutomatico' . "\0" . 'eliminado'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (GrupoMovimientosAutomatico $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getMovimientoManual()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMovimientoManual', []);

        return parent::getMovimientoManual();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setOrden($orden)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrden', [$orden]);

        return parent::setOrden($orden);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrden()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrden', []);

        return parent::getOrden();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombre($nombre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombre', [$nombre]);

        return parent::setNombre($nombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombre', []);

        return parent::getNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setProcesoFaena(\GestionFaenaBundle\Entity\ProcesoFaena $procesoFaena = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProcesoFaena', [$procesoFaena]);

        return parent::setProcesoFaena($procesoFaena);
    }

    /**
     * {@inheritDoc}
     */
    public function getProcesoFaena()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProcesoFaena', []);

        return parent::getProcesoFaena();
    }

    /**
     * {@inheritDoc}
     */
    public function addAutomatico(\GestionFaenaBundle\Entity\faena\MovimientoAutomatico $automatico)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAutomatico', [$automatico]);

        return parent::addAutomatico($automatico);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAutomatico(\GestionFaenaBundle\Entity\faena\MovimientoAutomatico $automatico)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAutomatico', [$automatico]);

        return parent::removeAutomatico($automatico);
    }

    /**
     * {@inheritDoc}
     */
    public function getAutomaticos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAutomaticos', []);

        return parent::getAutomaticos();
    }

    /**
     * {@inheritDoc}
     */
    public function setDetalle($detalle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDetalle', [$detalle]);

        return parent::setDetalle($detalle);
    }

    /**
     * {@inheritDoc}
     */
    public function getDetalle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDetalle', []);

        return parent::getDetalle();
    }

    /**
     * {@inheritDoc}
     */
    public function setManual($manual)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setManual', [$manual]);

        return parent::setManual($manual);
    }

    /**
     * {@inheritDoc}
     */
    public function getManual()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getManual', []);

        return parent::getManual();
    }

    /**
     * {@inheritDoc}
     */
    public function setPasoProceso(\GestionFaenaBundle\Entity\PasoProceso $pasoProceso = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPasoProceso', [$pasoProceso]);

        return parent::setPasoProceso($pasoProceso);
    }

    /**
     * {@inheritDoc}
     */
    public function getPasoProceso()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPasoProceso', []);

        return parent::getPasoProceso();
    }

    /**
     * {@inheritDoc}
     */
    public function setEliminado($eliminado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEliminado', [$eliminado]);

        return parent::setEliminado($eliminado);
    }

    /**
     * {@inheritDoc}
     */
    public function getEliminado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEliminado', []);

        return parent::getEliminado();
    }

}
