<?php

namespace Proxies\__CG__\GestionFaenaBundle\Entity\faena;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ConceptoMovimiento extends \GestionFaenaBundle\Entity\faena\ConceptoMovimiento implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'GestionFaenaBundle\\Entity\\faena\\ConceptoMovimiento' . "\0" . 'id', '' . "\0" . 'GestionFaenaBundle\\Entity\\faena\\ConceptoMovimiento' . "\0" . 'concepto', '' . "\0" . 'GestionFaenaBundle\\Entity\\faena\\ConceptoMovimiento' . "\0" . 'resumido', '' . "\0" . 'GestionFaenaBundle\\Entity\\faena\\ConceptoMovimiento' . "\0" . 'transforma'];
        }

        return ['__isInitialized__', '' . "\0" . 'GestionFaenaBundle\\Entity\\faena\\ConceptoMovimiento' . "\0" . 'id', '' . "\0" . 'GestionFaenaBundle\\Entity\\faena\\ConceptoMovimiento' . "\0" . 'concepto', '' . "\0" . 'GestionFaenaBundle\\Entity\\faena\\ConceptoMovimiento' . "\0" . 'resumido', '' . "\0" . 'GestionFaenaBundle\\Entity\\faena\\ConceptoMovimiento' . "\0" . 'transforma'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (ConceptoMovimiento $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getAtributoConcepto(\GestionFaenaBundle\Entity\gestionBD\ArticuloAtributoConcepto $apf)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAtributoConcepto', [$apf]);

        return parent::getAtributoConcepto($apf);
    }

    /**
     * {@inheritDoc}
     */
    public function manejaAtributo(\GestionFaenaBundle\Entity\gestionBD\AtributoProceso $atributo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'manejaAtributo', [$atributo]);

        return parent::manejaAtributo($atributo);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setConcepto($concepto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setConcepto', [$concepto]);

        return parent::setConcepto($concepto);
    }

    /**
     * {@inheritDoc}
     */
    public function getConcepto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConcepto', []);

        return parent::getConcepto();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function setTransforma($transforma)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTransforma', [$transforma]);

        return parent::setTransforma($transforma);
    }

    /**
     * {@inheritDoc}
     */
    public function getTransforma()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTransforma', []);

        return parent::getTransforma();
    }

    /**
     * {@inheritDoc}
     */
    public function setResumido($resumido)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setResumido', [$resumido]);

        return parent::setResumido($resumido);
    }

    /**
     * {@inheritDoc}
     */
    public function getResumido()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getResumido', []);

        return parent::getResumido();
    }

}
