<?php

namespace Proxies\__CG__\GestionFaenaBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ProcesoInicio extends \GestionFaenaBundle\Entity\ProcesoInicio implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__'];
        }

        return ['__isInitialized__'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (ProcesoInicio $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getType', []);

        return parent::getType();
    }

    /**
     * {@inheritDoc}
     */
    public function getInstance()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInstance', []);

        return parent::getInstance();
    }

    /**
     * {@inheritDoc}
     */
    public function atributoAsignadoAArticulo(\GestionFaenaBundle\Entity\gestionBD\Articulo $articulo, \GestionFaenaBundle\Entity\gestionBD\AtributoAbstracto $atributo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'atributoAsignadoAArticulo', [$articulo, $atributo]);

        return parent::atributoAsignadoAArticulo($articulo, $atributo);
    }

    /**
     * {@inheritDoc}
     */
    public function getConceptosOfVentas()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConceptosOfVentas', []);

        return parent::getConceptosOfVentas();
    }

    /**
     * {@inheritDoc}
     */
    public function existeArticuloDefinidoManejoStock(\GestionFaenaBundle\Entity\gestionBD\Articulo $articulo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'existeArticuloDefinidoManejoStock', [$articulo]);

        return parent::existeArticuloDefinidoManejoStock($articulo);
    }

    /**
     * {@inheritDoc}
     */
    public function existeArticuloConIdDefinidoManejoStock($idArticulo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'existeArticuloConIdDefinidoManejoStock', [$idArticulo]);

        return parent::existeArticuloConIdDefinidoManejoStock($idArticulo);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombre($nombre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombre', [$nombre]);

        return parent::setNombre($nombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombre', []);

        return parent::getNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function addArticulo(\GestionFaenaBundle\Entity\gestionBD\ArticuloProcesoFaena $articulo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addArticulo', [$articulo]);

        return parent::addArticulo($articulo);
    }

    /**
     * {@inheritDoc}
     */
    public function removeArticulo(\GestionFaenaBundle\Entity\gestionBD\ArticuloProcesoFaena $articulo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeArticulo', [$articulo]);

        return parent::removeArticulo($articulo);
    }

    /**
     * {@inheritDoc}
     */
    public function getArticulos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArticulos', []);

        return parent::getArticulos();
    }

    /**
     * {@inheritDoc}
     */
    public function addProcesosOrigen(\GestionFaenaBundle\Entity\ProcesoFaena $procesosOrigen)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addProcesosOrigen', [$procesosOrigen]);

        return parent::addProcesosOrigen($procesosOrigen);
    }

    /**
     * {@inheritDoc}
     */
    public function removeProcesosOrigen(\GestionFaenaBundle\Entity\ProcesoFaena $procesosOrigen)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeProcesosOrigen', [$procesosOrigen]);

        return parent::removeProcesosOrigen($procesosOrigen);
    }

    /**
     * {@inheritDoc}
     */
    public function getProcesosOrigen()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProcesosOrigen', []);

        return parent::getProcesosOrigen();
    }

    /**
     * {@inheritDoc}
     */
    public function addProcesosDestino(\GestionFaenaBundle\Entity\ProcesoFaena $procesosDestino)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addProcesosDestino', [$procesosDestino]);

        return parent::addProcesosDestino($procesosDestino);
    }

    /**
     * {@inheritDoc}
     */
    public function removeProcesosDestino(\GestionFaenaBundle\Entity\ProcesoFaena $procesosDestino)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeProcesosDestino', [$procesosDestino]);

        return parent::removeProcesosDestino($procesosDestino);
    }

    /**
     * {@inheritDoc}
     */
    public function getProcesosDestino()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProcesosDestino', []);

        return parent::getProcesosDestino();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function setActivo($activo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActivo', [$activo]);

        return parent::setActivo($activo);
    }

    /**
     * {@inheritDoc}
     */
    public function getActivo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActivo', []);

        return parent::getActivo();
    }

    /**
     * {@inheritDoc}
     */
    public function getArticulosActivos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArticulosActivos', []);

        return parent::getArticulosActivos();
    }

    /**
     * {@inheritDoc}
     */
    public function addConcepto(\GestionFaenaBundle\Entity\faena\ConceptoMovimiento $concepto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addConcepto', [$concepto]);

        return parent::addConcepto($concepto);
    }

    /**
     * {@inheritDoc}
     */
    public function removeConcepto(\GestionFaenaBundle\Entity\faena\ConceptoMovimiento $concepto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeConcepto', [$concepto]);

        return parent::removeConcepto($concepto);
    }

    /**
     * {@inheritDoc}
     */
    public function getConceptos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConceptos', []);

        return parent::getConceptos();
    }

    /**
     * {@inheritDoc}
     */
    public function addUsuario(\AppBundle\Entity\User $usuario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addUsuario', [$usuario]);

        return parent::addUsuario($usuario);
    }

    /**
     * {@inheritDoc}
     */
    public function removeUsuario(\AppBundle\Entity\User $usuario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeUsuario', [$usuario]);

        return parent::removeUsuario($usuario);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsuarios()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuarios', []);

        return parent::getUsuarios();
    }

    /**
     * {@inheritDoc}
     */
    public function addProcesosFaenaDiarium(\GestionFaenaBundle\Entity\faena\ProcesoFaenaDiaria $procesosFaenaDiarium)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addProcesosFaenaDiarium', [$procesosFaenaDiarium]);

        return parent::addProcesosFaenaDiarium($procesosFaenaDiarium);
    }

    /**
     * {@inheritDoc}
     */
    public function removeProcesosFaenaDiarium(\GestionFaenaBundle\Entity\faena\ProcesoFaenaDiaria $procesosFaenaDiarium)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeProcesosFaenaDiarium', [$procesosFaenaDiarium]);

        return parent::removeProcesosFaenaDiarium($procesosFaenaDiarium);
    }

    /**
     * {@inheritDoc}
     */
    public function getProcesosFaenaDiaria()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProcesosFaenaDiaria', []);

        return parent::getProcesosFaenaDiaria();
    }

    /**
     * {@inheritDoc}
     */
    public function addManejosStock(\GestionFaenaBundle\Entity\gestionBD\FactorCalculo $manejosStock)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addManejosStock', [$manejosStock]);

        return parent::addManejosStock($manejosStock);
    }

    /**
     * {@inheritDoc}
     */
    public function removeManejosStock(\GestionFaenaBundle\Entity\gestionBD\FactorCalculo $manejosStock)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeManejosStock', [$manejosStock]);

        return parent::removeManejosStock($manejosStock);
    }

    /**
     * {@inheritDoc}
     */
    public function getManejosStock()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getManejosStock', []);

        return parent::getManejosStock();
    }

    /**
     * {@inheritDoc}
     */
    public function getArticulosStock()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArticulosStock', []);

        return parent::getArticulosStock();
    }

    /**
     * {@inheritDoc}
     */
    public function setPermanente($permanente)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPermanente', [$permanente]);

        return parent::setPermanente($permanente);
    }

    /**
     * {@inheritDoc}
     */
    public function getPermanente()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPermanente', []);

        return parent::getPermanente();
    }

    /**
     * {@inheritDoc}
     */
    public function setOrden($orden)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrden', [$orden]);

        return parent::setOrden($orden);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrden()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrden', []);

        return parent::getOrden();
    }

    /**
     * {@inheritDoc}
     */
    public function addAjuste(\GestionFaenaBundle\Entity\ProcesoFaena $ajuste)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAjuste', [$ajuste]);

        return parent::addAjuste($ajuste);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAjuste(\GestionFaenaBundle\Entity\ProcesoFaena $ajuste)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAjuste', [$ajuste]);

        return parent::removeAjuste($ajuste);
    }

    /**
     * {@inheritDoc}
     */
    public function getAjustes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAjustes', []);

        return parent::getAjustes();
    }

    /**
     * {@inheritDoc}
     */
    public function getAjusteAAplicar(\GestionFaenaBundle\Entity\faena\TipoMovimientoConcepto $tipoMovimiento, \GestionFaenaBundle\Entity\faena\ConceptoMovimiento $conceptoMovimiento, \GestionFaenaBundle\Entity\gestionBD\Articulo $articulo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAjusteAAplicar', [$tipoMovimiento, $conceptoMovimiento, $articulo]);

        return parent::getAjusteAAplicar($tipoMovimiento, $conceptoMovimiento, $articulo);
    }

    /**
     * {@inheritDoc}
     */
    public function setProcesosDestinoDefault(\GestionFaenaBundle\Entity\ProcesoFaena $procesosDestinoDefault = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProcesosDestinoDefault', [$procesosDestinoDefault]);

        return parent::setProcesosDestinoDefault($procesosDestinoDefault);
    }

    /**
     * {@inheritDoc}
     */
    public function getProcesosDestinoDefault()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProcesosDestinoDefault', []);

        return parent::getProcesosDestinoDefault();
    }

    /**
     * {@inheritDoc}
     */
    public function setRomanea($romanea)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRomanea', [$romanea]);

        return parent::setRomanea($romanea);
    }

    /**
     * {@inheritDoc}
     */
    public function getRomanea()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRomanea', []);

        return parent::getRomanea();
    }

    /**
     * {@inheritDoc}
     */
    public function setArticuloBase(\GestionFaenaBundle\Entity\gestionBD\Articulo $articuloBase = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArticuloBase', [$articuloBase]);

        return parent::setArticuloBase($articuloBase);
    }

    /**
     * {@inheritDoc}
     */
    public function getArticuloBase()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArticuloBase', []);

        return parent::getArticuloBase();
    }

    /**
     * {@inheritDoc}
     */
    public function setAtributoAbstractoBase(\GestionFaenaBundle\Entity\gestionBD\AtributoAbstracto $atributoAbstractoBase = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAtributoAbstractoBase', [$atributoAbstractoBase]);

        return parent::setAtributoAbstractoBase($atributoAbstractoBase);
    }

    /**
     * {@inheritDoc}
     */
    public function getAtributoAbstractoBase()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAtributoAbstractoBase', []);

        return parent::getAtributoAbstractoBase();
    }

    /**
     * {@inheritDoc}
     */
    public function addAutomatico(\GestionFaenaBundle\Entity\faena\MovimientoAutomatico $automatico)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAutomatico', [$automatico]);

        return parent::addAutomatico($automatico);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAutomatico(\GestionFaenaBundle\Entity\faena\MovimientoAutomatico $automatico)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAutomatico', [$automatico]);

        return parent::removeAutomatico($automatico);
    }

    /**
     * {@inheritDoc}
     */
    public function getAutomaticos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAutomaticos', []);

        return parent::getAutomaticos();
    }

    /**
     * {@inheritDoc}
     */
    public function setGeneraTransito($generaTransito)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGeneraTransito', [$generaTransito]);

        return parent::setGeneraTransito($generaTransito);
    }

    /**
     * {@inheritDoc}
     */
    public function getGeneraTransito()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGeneraTransito', []);

        return parent::getGeneraTransito();
    }

    /**
     * {@inheritDoc}
     */
    public function setPromedioDefault($promedioDefault)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPromedioDefault', [$promedioDefault]);

        return parent::setPromedioDefault($promedioDefault);
    }

    /**
     * {@inheritDoc}
     */
    public function getPromedioDefault()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPromedioDefault', []);

        return parent::getPromedioDefault();
    }

    /**
     * {@inheritDoc}
     */
    public function addPaso(\GestionFaenaBundle\Entity\PasoProceso $paso)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPaso', [$paso]);

        return parent::addPaso($paso);
    }

    /**
     * {@inheritDoc}
     */
    public function removePaso(\GestionFaenaBundle\Entity\PasoProceso $paso)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePaso', [$paso]);

        return parent::removePaso($paso);
    }

    /**
     * {@inheritDoc}
     */
    public function getPasos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPasos', []);

        return parent::getPasos();
    }

    /**
     * {@inheritDoc}
     */
    public function setGeneraVentas($generaVentas)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGeneraVentas', [$generaVentas]);

        return parent::setGeneraVentas($generaVentas);
    }

    /**
     * {@inheritDoc}
     */
    public function getGeneraVentas()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGeneraVentas', []);

        return parent::getGeneraVentas();
    }

    /**
     * {@inheritDoc}
     */
    public function addVenta(\GestionFaenaBundle\Entity\ConceptoVenta $venta)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addVenta', [$venta]);

        return parent::addVenta($venta);
    }

    /**
     * {@inheritDoc}
     */
    public function removeVenta(\GestionFaenaBundle\Entity\ConceptoVenta $venta)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeVenta', [$venta]);

        return parent::removeVenta($venta);
    }

    /**
     * {@inheritDoc}
     */
    public function getVentas()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVentas', []);

        return parent::getVentas();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdmiteCombinado($admiteCombinado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdmiteCombinado', [$admiteCombinado]);

        return parent::setAdmiteCombinado($admiteCombinado);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdmiteCombinado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdmiteCombinado', []);

        return parent::getAdmiteCombinado();
    }

    /**
     * {@inheritDoc}
     */
    public function addAtributosArticulo(\GestionFaenaBundle\Entity\faena\AtributoPorArticuloPorProceso $atributosArticulo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAtributosArticulo', [$atributosArticulo]);

        return parent::addAtributosArticulo($atributosArticulo);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAtributosArticulo(\GestionFaenaBundle\Entity\faena\AtributoPorArticuloPorProceso $atributosArticulo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAtributosArticulo', [$atributosArticulo]);

        return parent::removeAtributosArticulo($atributosArticulo);
    }

    /**
     * {@inheritDoc}
     */
    public function getAtributosArticulo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAtributosArticulo', []);

        return parent::getAtributosArticulo();
    }

    /**
     * {@inheritDoc}
     */
    public function setAtributoVenta(\GestionFaenaBundle\Entity\gestionBD\AtributoAbstracto $atributoVenta = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAtributoVenta', [$atributoVenta]);

        return parent::setAtributoVenta($atributoVenta);
    }

    /**
     * {@inheritDoc}
     */
    public function getAtributoVenta()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAtributoVenta', []);

        return parent::getAtributoVenta();
    }

    /**
     * {@inheritDoc}
     */
    public function addEntidadesConcepto(\GestionVentasBundle\Entity\options\EntidadExternaConcepto $entidadesConcepto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addEntidadesConcepto', [$entidadesConcepto]);

        return parent::addEntidadesConcepto($entidadesConcepto);
    }

    /**
     * {@inheritDoc}
     */
    public function removeEntidadesConcepto(\GestionVentasBundle\Entity\options\EntidadExternaConcepto $entidadesConcepto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeEntidadesConcepto', [$entidadesConcepto]);

        return parent::removeEntidadesConcepto($entidadesConcepto);
    }

    /**
     * {@inheritDoc}
     */
    public function getEntidadesConcepto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEntidadesConcepto', []);

        return parent::getEntidadesConcepto();
    }

    /**
     * {@inheritDoc}
     */
    public function setUnidadMedidaventa(\GestionFaenaBundle\Entity\gestionBD\UnidadMedida $unidadMedidaventa = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUnidadMedidaventa', [$unidadMedidaventa]);

        return parent::setUnidadMedidaventa($unidadMedidaventa);
    }

    /**
     * {@inheritDoc}
     */
    public function getUnidadMedidaventa()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUnidadMedidaventa', []);

        return parent::getUnidadMedidaventa();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsTransito($isTransito)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsTransito', [$isTransito]);

        return parent::setIsTransito($isTransito);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsTransito()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsTransito', []);

        return parent::getIsTransito();
    }

}
